# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ai_window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QGridLayout,
    QHBoxLayout, QLabel, QLayout, QMainWindow,
    QPushButton, QRadioButton, QSizePolicy, QSlider,
    QSpacerItem, QSplitter, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1743, 1001)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_5 = QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_3 = QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.pushButton_9 = QPushButton(self.frame_2)
        self.pushButton_9.setObjectName(u"pushButton_9")

        self.horizontalLayout_3.addWidget(self.pushButton_9)

        self.pushButton_7 = QPushButton(self.frame_2)
        self.pushButton_7.setObjectName(u"pushButton_7")

        self.horizontalLayout_3.addWidget(self.pushButton_7)

        self.pushButton_3 = QPushButton(self.frame_2)
        self.pushButton_3.setObjectName(u"pushButton_3")

        self.horizontalLayout_3.addWidget(self.pushButton_3)

        self.pushButton_2 = QPushButton(self.frame_2)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.horizontalLayout_3.addWidget(self.pushButton_2)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer)


        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)


        self.horizontalLayout_2.addWidget(self.frame_2)


        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SizeConstraint.SetMaximumSize)
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")

        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)


        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)


        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SizeConstraint.SetFixedSize)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(0, 0))
        self.frame.setMaximumSize(QSize(300, 50000))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.frame_4 = QFrame(self.frame)
        self.frame_4.setObjectName(u"frame_4")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy1)
        self.frame_4.setMaximumSize(QSize(300, 16777215))
        self.frame_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.splitter_8 = QSplitter(self.frame_4)
        self.splitter_8.setObjectName(u"splitter_8")
        self.splitter_8.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_8.setHandleWidth(0)
        self.label_5 = QLabel(self.splitter_8)
        self.label_5.setObjectName(u"label_5")
        self.splitter_8.addWidget(self.label_5)
        self.pushButton_8 = QPushButton(self.splitter_8)
        self.pushButton_8.setObjectName(u"pushButton_8")
        sizePolicy1.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy1)
        self.pushButton_8.setMinimumSize(QSize(0, 0))
        self.pushButton_8.setMaximumSize(QSize(40, 40))
        self.splitter_8.addWidget(self.pushButton_8)

        self.verticalLayout_7.addWidget(self.splitter_8)

        self.label_8 = QLabel(self.frame_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_7.addWidget(self.label_8)

        self.splitter_9 = QSplitter(self.frame_4)
        self.splitter_9.setObjectName(u"splitter_9")
        self.splitter_9.setOrientation(Qt.Orientation.Vertical)
        self.splitter_9.setHandleWidth(0)
        self.splitter_10 = QSplitter(self.splitter_9)
        self.splitter_10.setObjectName(u"splitter_10")
        self.splitter_10.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_10.setHandleWidth(0)
        self.pushButton_13 = QPushButton(self.splitter_10)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.splitter_10.addWidget(self.pushButton_13)
        self.pushButton_14 = QPushButton(self.splitter_10)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.splitter_10.addWidget(self.pushButton_14)
        self.pushButton_15 = QPushButton(self.splitter_10)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.splitter_10.addWidget(self.pushButton_15)
        self.splitter_9.addWidget(self.splitter_10)
        self.splitter_11 = QSplitter(self.splitter_9)
        self.splitter_11.setObjectName(u"splitter_11")
        self.splitter_11.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_11.setHandleWidth(0)
        self.pushButton_16 = QPushButton(self.splitter_11)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.splitter_11.addWidget(self.pushButton_16)
        self.pushButton_17 = QPushButton(self.splitter_11)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.splitter_11.addWidget(self.pushButton_17)
        self.pushButton_18 = QPushButton(self.splitter_11)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.splitter_11.addWidget(self.pushButton_18)
        self.splitter_9.addWidget(self.splitter_11)
        self.splitter_12 = QSplitter(self.splitter_9)
        self.splitter_12.setObjectName(u"splitter_12")
        self.splitter_12.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_12.setHandleWidth(0)
        self.pushButton_19 = QPushButton(self.splitter_12)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.splitter_12.addWidget(self.pushButton_19)
        self.pushButton_20 = QPushButton(self.splitter_12)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.splitter_12.addWidget(self.pushButton_20)
        self.pushButton_21 = QPushButton(self.splitter_12)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.splitter_12.addWidget(self.pushButton_21)
        self.splitter_9.addWidget(self.splitter_12)

        self.verticalLayout_7.addWidget(self.splitter_9)

        self.label_9 = QLabel(self.frame_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_7.addWidget(self.label_9)

        self.splitter_13 = QSplitter(self.frame_4)
        self.splitter_13.setObjectName(u"splitter_13")
        self.splitter_13.setOrientation(Qt.Orientation.Vertical)
        self.splitter_13.setHandleWidth(0)
        self.splitter_14 = QSplitter(self.splitter_13)
        self.splitter_14.setObjectName(u"splitter_14")
        self.splitter_14.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_14.setHandleWidth(0)
        self.pushButton_22 = QPushButton(self.splitter_14)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.splitter_14.addWidget(self.pushButton_22)
        self.pushButton_23 = QPushButton(self.splitter_14)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.splitter_14.addWidget(self.pushButton_23)
        self.pushButton_24 = QPushButton(self.splitter_14)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.splitter_14.addWidget(self.pushButton_24)
        self.splitter_13.addWidget(self.splitter_14)
        self.splitter_15 = QSplitter(self.splitter_13)
        self.splitter_15.setObjectName(u"splitter_15")
        self.splitter_15.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_15.setHandleWidth(0)
        self.pushButton_25 = QPushButton(self.splitter_15)
        self.pushButton_25.setObjectName(u"pushButton_25")
        self.splitter_15.addWidget(self.pushButton_25)
        self.pushButton_26 = QPushButton(self.splitter_15)
        self.pushButton_26.setObjectName(u"pushButton_26")
        self.splitter_15.addWidget(self.pushButton_26)
        self.pushButton_27 = QPushButton(self.splitter_15)
        self.pushButton_27.setObjectName(u"pushButton_27")
        self.splitter_15.addWidget(self.pushButton_27)
        self.splitter_13.addWidget(self.splitter_15)
        self.splitter_16 = QSplitter(self.splitter_13)
        self.splitter_16.setObjectName(u"splitter_16")
        self.splitter_16.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_16.setHandleWidth(0)
        self.pushButton_28 = QPushButton(self.splitter_16)
        self.pushButton_28.setObjectName(u"pushButton_28")
        self.splitter_16.addWidget(self.pushButton_28)
        self.pushButton_29 = QPushButton(self.splitter_16)
        self.pushButton_29.setObjectName(u"pushButton_29")
        self.splitter_16.addWidget(self.pushButton_29)
        self.pushButton_30 = QPushButton(self.splitter_16)
        self.pushButton_30.setObjectName(u"pushButton_30")
        self.splitter_16.addWidget(self.pushButton_30)
        self.splitter_13.addWidget(self.splitter_16)

        self.verticalLayout_7.addWidget(self.splitter_13)

        self.label_10 = QLabel(self.frame_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_7.addWidget(self.label_10)

        self.splitter_18 = QSplitter(self.frame_4)
        self.splitter_18.setObjectName(u"splitter_18")
        self.splitter_18.setOrientation(Qt.Orientation.Vertical)
        self.splitter_18.setHandleWidth(0)
        self.splitter_19 = QSplitter(self.splitter_18)
        self.splitter_19.setObjectName(u"splitter_19")
        self.splitter_19.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_19.setHandleWidth(0)
        self.pushButton_40 = QPushButton(self.splitter_19)
        self.pushButton_40.setObjectName(u"pushButton_40")
        self.splitter_19.addWidget(self.pushButton_40)
        self.pushButton_41 = QPushButton(self.splitter_19)
        self.pushButton_41.setObjectName(u"pushButton_41")
        self.splitter_19.addWidget(self.pushButton_41)
        self.pushButton_42 = QPushButton(self.splitter_19)
        self.pushButton_42.setObjectName(u"pushButton_42")
        self.splitter_19.addWidget(self.pushButton_42)
        self.splitter_18.addWidget(self.splitter_19)
        self.splitter_20 = QSplitter(self.splitter_18)
        self.splitter_20.setObjectName(u"splitter_20")
        self.splitter_20.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_20.setHandleWidth(0)
        self.pushButton_43 = QPushButton(self.splitter_20)
        self.pushButton_43.setObjectName(u"pushButton_43")
        self.splitter_20.addWidget(self.pushButton_43)
        self.pushButton_44 = QPushButton(self.splitter_20)
        self.pushButton_44.setObjectName(u"pushButton_44")
        self.splitter_20.addWidget(self.pushButton_44)
        self.pushButton_45 = QPushButton(self.splitter_20)
        self.pushButton_45.setObjectName(u"pushButton_45")
        self.splitter_20.addWidget(self.pushButton_45)
        self.splitter_18.addWidget(self.splitter_20)
        self.splitter_21 = QSplitter(self.splitter_18)
        self.splitter_21.setObjectName(u"splitter_21")
        self.splitter_21.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_21.setHandleWidth(0)
        self.pushButton_46 = QPushButton(self.splitter_21)
        self.pushButton_46.setObjectName(u"pushButton_46")
        self.splitter_21.addWidget(self.pushButton_46)
        self.pushButton_47 = QPushButton(self.splitter_21)
        self.pushButton_47.setObjectName(u"pushButton_47")
        self.splitter_21.addWidget(self.pushButton_47)
        self.pushButton_48 = QPushButton(self.splitter_21)
        self.pushButton_48.setObjectName(u"pushButton_48")
        self.splitter_21.addWidget(self.pushButton_48)
        self.splitter_18.addWidget(self.splitter_21)

        self.verticalLayout_7.addWidget(self.splitter_18)

        self.label_11 = QLabel(self.frame_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_7.addWidget(self.label_11)

        self.splitter_22 = QSplitter(self.frame_4)
        self.splitter_22.setObjectName(u"splitter_22")
        self.splitter_22.setOrientation(Qt.Orientation.Vertical)
        self.splitter_22.setHandleWidth(0)
        self.splitter_23 = QSplitter(self.splitter_22)
        self.splitter_23.setObjectName(u"splitter_23")
        self.splitter_23.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_23.setHandleWidth(0)
        self.pushButton_49 = QPushButton(self.splitter_23)
        self.pushButton_49.setObjectName(u"pushButton_49")
        self.splitter_23.addWidget(self.pushButton_49)
        self.pushButton_50 = QPushButton(self.splitter_23)
        self.pushButton_50.setObjectName(u"pushButton_50")
        self.splitter_23.addWidget(self.pushButton_50)
        self.pushButton_51 = QPushButton(self.splitter_23)
        self.pushButton_51.setObjectName(u"pushButton_51")
        self.splitter_23.addWidget(self.pushButton_51)
        self.splitter_22.addWidget(self.splitter_23)
        self.splitter_24 = QSplitter(self.splitter_22)
        self.splitter_24.setObjectName(u"splitter_24")
        self.splitter_24.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_24.setHandleWidth(0)
        self.pushButton_52 = QPushButton(self.splitter_24)
        self.pushButton_52.setObjectName(u"pushButton_52")
        self.splitter_24.addWidget(self.pushButton_52)
        self.pushButton_53 = QPushButton(self.splitter_24)
        self.pushButton_53.setObjectName(u"pushButton_53")
        self.splitter_24.addWidget(self.pushButton_53)
        self.pushButton_54 = QPushButton(self.splitter_24)
        self.pushButton_54.setObjectName(u"pushButton_54")
        self.splitter_24.addWidget(self.pushButton_54)
        self.splitter_22.addWidget(self.splitter_24)
        self.splitter_25 = QSplitter(self.splitter_22)
        self.splitter_25.setObjectName(u"splitter_25")
        self.splitter_25.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_25.setHandleWidth(0)
        self.pushButton_55 = QPushButton(self.splitter_25)
        self.pushButton_55.setObjectName(u"pushButton_55")
        self.splitter_25.addWidget(self.pushButton_55)
        self.pushButton_56 = QPushButton(self.splitter_25)
        self.pushButton_56.setObjectName(u"pushButton_56")
        self.splitter_25.addWidget(self.pushButton_56)
        self.pushButton_57 = QPushButton(self.splitter_25)
        self.pushButton_57.setObjectName(u"pushButton_57")
        self.splitter_25.addWidget(self.pushButton_57)
        self.splitter_22.addWidget(self.splitter_25)

        self.verticalLayout_7.addWidget(self.splitter_22)


        self.verticalLayout_4.addWidget(self.frame_4)


        self.verticalLayout_2.addLayout(self.verticalLayout_4)

        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.frame_3 = QFrame(self.frame)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy1.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy1)
        self.frame_3.setMaximumSize(QSize(300, 16777215))
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_6 = QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.splitter_3 = QSplitter(self.frame_3)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_3.setHandleWidth(0)
        self.label = QLabel(self.splitter_3)
        self.label.setObjectName(u"label")
        self.splitter_3.addWidget(self.label)
        self.pushButton = QPushButton(self.splitter_3)
        self.pushButton.setObjectName(u"pushButton")
        sizePolicy1.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy1)
        self.pushButton.setMinimumSize(QSize(0, 0))
        self.pushButton.setMaximumSize(QSize(40, 40))
        self.splitter_3.addWidget(self.pushButton)

        self.verticalLayout_6.addWidget(self.splitter_3)

        self.label_4 = QLabel(self.frame_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_6.addWidget(self.label_4)

        self.splitter_4 = QSplitter(self.frame_3)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setOrientation(Qt.Orientation.Vertical)
        self.splitter_4.setHandleWidth(0)
        self.splitter_5 = QSplitter(self.splitter_4)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_5.setHandleWidth(0)
        self.radioButton = QRadioButton(self.splitter_5)
        self.radioButton.setObjectName(u"radioButton")
        self.splitter_5.addWidget(self.radioButton)
        self.radioButton_2 = QRadioButton(self.splitter_5)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.splitter_5.addWidget(self.radioButton_2)
        self.radioButton_3 = QRadioButton(self.splitter_5)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.splitter_5.addWidget(self.radioButton_3)
        self.splitter_4.addWidget(self.splitter_5)
        self.splitter_6 = QSplitter(self.splitter_4)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_6.setHandleWidth(0)
        self.horizontalSlider = QSlider(self.splitter_6)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_6.addWidget(self.horizontalSlider)
        self.label_3 = QLabel(self.splitter_6)
        self.label_3.setObjectName(u"label_3")
        self.splitter_6.addWidget(self.label_3)
        self.splitter_4.addWidget(self.splitter_6)

        self.verticalLayout_6.addWidget(self.splitter_4)

        self.label_6 = QLabel(self.frame_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_6.addWidget(self.label_6)

        self.splitter_7 = QSplitter(self.frame_3)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_7.setHandleWidth(0)
        self.radioButton_4 = QRadioButton(self.splitter_7)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.splitter_7.addWidget(self.radioButton_4)
        self.radioButton_5 = QRadioButton(self.splitter_7)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.splitter_7.addWidget(self.radioButton_5)
        self.radioButton_6 = QRadioButton(self.splitter_7)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.splitter_7.addWidget(self.radioButton_6)

        self.verticalLayout_6.addWidget(self.splitter_7)

        self.label_7 = QLabel(self.frame_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_6.addWidget(self.label_7)

        self.splitter_17 = QSplitter(self.frame_3)
        self.splitter_17.setObjectName(u"splitter_17")
        self.splitter_17.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_17.setHandleWidth(0)
        self.radioButton_7 = QRadioButton(self.splitter_17)
        self.radioButton_7.setObjectName(u"radioButton_7")
        self.splitter_17.addWidget(self.radioButton_7)
        self.radioButton_8 = QRadioButton(self.splitter_17)
        self.radioButton_8.setObjectName(u"radioButton_8")
        self.splitter_17.addWidget(self.radioButton_8)
        self.radioButton_9 = QRadioButton(self.splitter_17)
        self.radioButton_9.setObjectName(u"radioButton_9")
        self.splitter_17.addWidget(self.radioButton_9)

        self.verticalLayout_6.addWidget(self.splitter_17)

        self.label_12 = QLabel(self.frame_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_6.addWidget(self.label_12)

        self.splitter_26 = QSplitter(self.frame_3)
        self.splitter_26.setObjectName(u"splitter_26")
        self.splitter_26.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_26.setHandleWidth(0)
        self.radioButton_10 = QRadioButton(self.splitter_26)
        self.radioButton_10.setObjectName(u"radioButton_10")
        self.splitter_26.addWidget(self.radioButton_10)
        self.radioButton_11 = QRadioButton(self.splitter_26)
        self.radioButton_11.setObjectName(u"radioButton_11")
        self.splitter_26.addWidget(self.radioButton_11)
        self.radioButton_12 = QRadioButton(self.splitter_26)
        self.radioButton_12.setObjectName(u"radioButton_12")
        self.splitter_26.addWidget(self.radioButton_12)
        self.radioButton_13 = QRadioButton(self.splitter_26)
        self.radioButton_13.setObjectName(u"radioButton_13")
        self.splitter_26.addWidget(self.radioButton_13)

        self.verticalLayout_6.addWidget(self.splitter_26)


        self.verticalLayout_5.addWidget(self.frame_3)


        self.verticalLayout_2.addLayout(self.verticalLayout_5)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer)


        self.horizontalLayout.addLayout(self.verticalLayout_2)


        self.verticalLayout.addWidget(self.frame)


        self.gridLayout_4.addLayout(self.verticalLayout, 0, 1, 1, 1)


        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"save", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"ai tools", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"ai seting", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"parameters", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"tools", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"fire", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"set 1 ", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"set 2 ", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"set 3 ", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"set 4 ", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"set 5", None))
        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"set 6", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u"set 7 ", None))
        self.pushButton_20.setText(QCoreApplication.translate("MainWindow", u"set 8 ", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"set 9 ", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"water", None))
        self.pushButton_22.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.pushButton_23.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.pushButton_24.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.pushButton_25.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.pushButton_26.setText(QCoreApplication.translate("MainWindow", u"14", None))
        self.pushButton_27.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.pushButton_28.setText(QCoreApplication.translate("MainWindow", u"16", None))
        self.pushButton_29.setText(QCoreApplication.translate("MainWindow", u"17", None))
        self.pushButton_30.setText(QCoreApplication.translate("MainWindow", u"18 ", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"list", None))
        self.pushButton_40.setText(QCoreApplication.translate("MainWindow", u"19", None))
        self.pushButton_41.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.pushButton_42.setText(QCoreApplication.translate("MainWindow", u"21", None))
        self.pushButton_43.setText(QCoreApplication.translate("MainWindow", u"22", None))
        self.pushButton_44.setText(QCoreApplication.translate("MainWindow", u"23", None))
        self.pushButton_45.setText(QCoreApplication.translate("MainWindow", u"24", None))
        self.pushButton_46.setText(QCoreApplication.translate("MainWindow", u"25", None))
        self.pushButton_47.setText(QCoreApplication.translate("MainWindow", u"26", None))
        self.pushButton_48.setText(QCoreApplication.translate("MainWindow", u"27", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"wind", None))
        self.pushButton_49.setText(QCoreApplication.translate("MainWindow", u"28", None))
        self.pushButton_50.setText(QCoreApplication.translate("MainWindow", u"29", None))
        self.pushButton_51.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.pushButton_52.setText(QCoreApplication.translate("MainWindow", u"31", None))
        self.pushButton_53.setText(QCoreApplication.translate("MainWindow", u"32", None))
        self.pushButton_54.setText(QCoreApplication.translate("MainWindow", u"33", None))
        self.pushButton_55.setText(QCoreApplication.translate("MainWindow", u"34", None))
        self.pushButton_56.setText(QCoreApplication.translate("MainWindow", u"35", None))
        self.pushButton_57.setText(QCoreApplication.translate("MainWindow", u"36", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"ai setting", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"haoss", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"set 1", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"set 2 ", None))
        self.radioButton_3.setText(QCoreApplication.translate("MainWindow", u"set 3 ", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"0%", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"entensiv", None))
        self.radioButton_4.setText(QCoreApplication.translate("MainWindow", u"low", None))
        self.radioButton_5.setText(QCoreApplication.translate("MainWindow", u"mediom", None))
        self.radioButton_6.setText(QCoreApplication.translate("MainWindow", u"high", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"spead animation", None))
        self.radioButton_7.setText(QCoreApplication.translate("MainWindow", u"low", None))
        self.radioButton_8.setText(QCoreApplication.translate("MainWindow", u"mediom", None))
        self.radioButton_9.setText(QCoreApplication.translate("MainWindow", u"high", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"textur", None))
        self.radioButton_10.setText(QCoreApplication.translate("MainWindow", u"nune", None))
        self.radioButton_11.setText(QCoreApplication.translate("MainWindow", u"low", None))
        self.radioButton_12.setText(QCoreApplication.translate("MainWindow", u"mediom", None))
        self.radioButton_13.setText(QCoreApplication.translate("MainWindow", u"high", None))
    # retranslateUi

