# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'fire_tool.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QGroupBox,
    QLabel, QPushButton, QSizePolicy, QSpinBox,
    QSplitter, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(280, 594)
        Form.setMaximumSize(QSize(280, 16777215))
        self.gridLayout_3 = QGridLayout(Form)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setEnabled(True)
        self.frame.setMaximumSize(QSize(280, 16777215))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_2 = QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.label_185 = QLabel(self.frame)
        self.label_185.setObjectName(u"label_185")
        self.label_185.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_185, 6, 0, 1, 1)

        self.splitter_2 = QSplitter(self.frame)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_2.setHandleWidth(0)
        self.pushButton_282 = QPushButton(self.splitter_2)
        self.pushButton_282.setObjectName(u"pushButton_282")
        self.splitter_2.addWidget(self.pushButton_282)
        self.pushButton_283 = QPushButton(self.splitter_2)
        self.pushButton_283.setObjectName(u"pushButton_283")
        self.splitter_2.addWidget(self.pushButton_283)
        self.pushButton_284 = QPushButton(self.splitter_2)
        self.pushButton_284.setObjectName(u"pushButton_284")
        self.splitter_2.addWidget(self.pushButton_284)
        self.pushButton_285 = QPushButton(self.splitter_2)
        self.pushButton_285.setObjectName(u"pushButton_285")
        self.splitter_2.addWidget(self.pushButton_285)

        self.gridLayout_2.addWidget(self.splitter_2, 2, 0, 1, 1)

        self.splitter = QSplitter(self.frame)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(0)
        self.label_183 = QLabel(self.splitter)
        self.label_183.setObjectName(u"label_183")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_183.sizePolicy().hasHeightForWidth())
        self.label_183.setSizePolicy(sizePolicy)
        self.label_183.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter.addWidget(self.label_183)
        self.pushButton_281 = QPushButton(self.splitter)
        self.pushButton_281.setObjectName(u"pushButton_281")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pushButton_281.sizePolicy().hasHeightForWidth())
        self.pushButton_281.setSizePolicy(sizePolicy1)
        self.pushButton_281.setMaximumSize(QSize(30, 30))
        self.splitter.addWidget(self.pushButton_281)

        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 1)

        self.groupBox_19 = QGroupBox(self.frame)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.gridLayout = QGridLayout(self.groupBox_19)
        self.gridLayout.setObjectName(u"gridLayout")
        self.splitter_383 = QSplitter(self.groupBox_19)
        self.splitter_383.setObjectName(u"splitter_383")
        self.splitter_383.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_383.setHandleWidth(0)
        self.label_195 = QLabel(self.splitter_383)
        self.label_195.setObjectName(u"label_195")
        self.splitter_383.addWidget(self.label_195)
        self.spinBox_136 = QSpinBox(self.splitter_383)
        self.spinBox_136.setObjectName(u"spinBox_136")
        self.spinBox_136.setMaximumSize(QSize(100, 16777215))
        self.splitter_383.addWidget(self.spinBox_136)

        self.gridLayout.addWidget(self.splitter_383, 0, 0, 1, 1)

        self.splitter_376 = QSplitter(self.groupBox_19)
        self.splitter_376.setObjectName(u"splitter_376")
        self.splitter_376.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_376.setHandleWidth(0)
        self.label_188 = QLabel(self.splitter_376)
        self.label_188.setObjectName(u"label_188")
        self.splitter_376.addWidget(self.label_188)
        self.spinBox_129 = QSpinBox(self.splitter_376)
        self.spinBox_129.setObjectName(u"spinBox_129")
        self.spinBox_129.setMaximumSize(QSize(100, 16777215))
        self.splitter_376.addWidget(self.spinBox_129)

        self.gridLayout.addWidget(self.splitter_376, 1, 0, 1, 1)

        self.splitter_375 = QSplitter(self.groupBox_19)
        self.splitter_375.setObjectName(u"splitter_375")
        self.splitter_375.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_375.setHandleWidth(0)
        self.label_187 = QLabel(self.splitter_375)
        self.label_187.setObjectName(u"label_187")
        self.splitter_375.addWidget(self.label_187)
        self.spinBox_128 = QSpinBox(self.splitter_375)
        self.spinBox_128.setObjectName(u"spinBox_128")
        self.splitter_375.addWidget(self.spinBox_128)

        self.gridLayout.addWidget(self.splitter_375, 2, 0, 1, 1)

        self.splitter_374 = QSplitter(self.groupBox_19)
        self.splitter_374.setObjectName(u"splitter_374")
        self.splitter_374.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_374.setHandleWidth(0)
        self.label_186 = QLabel(self.splitter_374)
        self.label_186.setObjectName(u"label_186")
        self.splitter_374.addWidget(self.label_186)
        self.spinBox_127 = QSpinBox(self.splitter_374)
        self.spinBox_127.setObjectName(u"spinBox_127")
        sizePolicy1.setHeightForWidth(self.spinBox_127.sizePolicy().hasHeightForWidth())
        self.spinBox_127.setSizePolicy(sizePolicy1)
        self.spinBox_127.setMinimumSize(QSize(100, 0))
        self.spinBox_127.setMaximumSize(QSize(120, 16777215))
        self.splitter_374.addWidget(self.spinBox_127)

        self.gridLayout.addWidget(self.splitter_374, 3, 0, 1, 1)

        self.splitter_384 = QSplitter(self.groupBox_19)
        self.splitter_384.setObjectName(u"splitter_384")
        self.splitter_384.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_384.setHandleWidth(0)
        self.label_196 = QLabel(self.splitter_384)
        self.label_196.setObjectName(u"label_196")
        self.splitter_384.addWidget(self.label_196)
        self.spinBox_137 = QSpinBox(self.splitter_384)
        self.spinBox_137.setObjectName(u"spinBox_137")
        sizePolicy1.setHeightForWidth(self.spinBox_137.sizePolicy().hasHeightForWidth())
        self.spinBox_137.setSizePolicy(sizePolicy1)
        self.spinBox_137.setMinimumSize(QSize(100, 0))
        self.spinBox_137.setMaximumSize(QSize(120, 16777215))
        self.splitter_384.addWidget(self.spinBox_137)

        self.gridLayout.addWidget(self.splitter_384, 4, 0, 1, 1)

        self.splitter_381 = QSplitter(self.groupBox_19)
        self.splitter_381.setObjectName(u"splitter_381")
        self.splitter_381.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_381.setHandleWidth(0)
        self.label_193 = QLabel(self.splitter_381)
        self.label_193.setObjectName(u"label_193")
        self.splitter_381.addWidget(self.label_193)
        self.spinBox_134 = QSpinBox(self.splitter_381)
        self.spinBox_134.setObjectName(u"spinBox_134")
        sizePolicy1.setHeightForWidth(self.spinBox_134.sizePolicy().hasHeightForWidth())
        self.spinBox_134.setSizePolicy(sizePolicy1)
        self.spinBox_134.setMinimumSize(QSize(100, 0))
        self.spinBox_134.setMaximumSize(QSize(120, 16777215))
        self.splitter_381.addWidget(self.spinBox_134)

        self.gridLayout.addWidget(self.splitter_381, 5, 0, 1, 1)

        self.splitter_377 = QSplitter(self.groupBox_19)
        self.splitter_377.setObjectName(u"splitter_377")
        self.splitter_377.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_377.setHandleWidth(0)
        self.label_189 = QLabel(self.splitter_377)
        self.label_189.setObjectName(u"label_189")
        self.splitter_377.addWidget(self.label_189)
        self.spinBox_130 = QSpinBox(self.splitter_377)
        self.spinBox_130.setObjectName(u"spinBox_130")
        sizePolicy1.setHeightForWidth(self.spinBox_130.sizePolicy().hasHeightForWidth())
        self.spinBox_130.setSizePolicy(sizePolicy1)
        self.spinBox_130.setMinimumSize(QSize(100, 0))
        self.spinBox_130.setMaximumSize(QSize(120, 16777215))
        self.splitter_377.addWidget(self.spinBox_130)

        self.gridLayout.addWidget(self.splitter_377, 6, 0, 1, 1)

        self.splitter_378 = QSplitter(self.groupBox_19)
        self.splitter_378.setObjectName(u"splitter_378")
        self.splitter_378.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_378.setHandleWidth(0)
        self.label_190 = QLabel(self.splitter_378)
        self.label_190.setObjectName(u"label_190")
        self.splitter_378.addWidget(self.label_190)
        self.spinBox_131 = QSpinBox(self.splitter_378)
        self.spinBox_131.setObjectName(u"spinBox_131")
        sizePolicy1.setHeightForWidth(self.spinBox_131.sizePolicy().hasHeightForWidth())
        self.spinBox_131.setSizePolicy(sizePolicy1)
        self.spinBox_131.setMinimumSize(QSize(100, 0))
        self.spinBox_131.setMaximumSize(QSize(120, 16777215))
        self.splitter_378.addWidget(self.spinBox_131)

        self.gridLayout.addWidget(self.splitter_378, 7, 0, 1, 1)

        self.splitter_379 = QSplitter(self.groupBox_19)
        self.splitter_379.setObjectName(u"splitter_379")
        self.splitter_379.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_379.setHandleWidth(0)
        self.label_191 = QLabel(self.splitter_379)
        self.label_191.setObjectName(u"label_191")
        self.splitter_379.addWidget(self.label_191)
        self.spinBox_132 = QSpinBox(self.splitter_379)
        self.spinBox_132.setObjectName(u"spinBox_132")
        sizePolicy1.setHeightForWidth(self.spinBox_132.sizePolicy().hasHeightForWidth())
        self.spinBox_132.setSizePolicy(sizePolicy1)
        self.spinBox_132.setMinimumSize(QSize(100, 0))
        self.spinBox_132.setMaximumSize(QSize(120, 16777215))
        self.splitter_379.addWidget(self.spinBox_132)

        self.gridLayout.addWidget(self.splitter_379, 8, 0, 1, 1)

        self.splitter_380 = QSplitter(self.groupBox_19)
        self.splitter_380.setObjectName(u"splitter_380")
        self.splitter_380.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_380.setHandleWidth(0)
        self.label_192 = QLabel(self.splitter_380)
        self.label_192.setObjectName(u"label_192")
        self.splitter_380.addWidget(self.label_192)
        self.spinBox_133 = QSpinBox(self.splitter_380)
        self.spinBox_133.setObjectName(u"spinBox_133")
        sizePolicy1.setHeightForWidth(self.spinBox_133.sizePolicy().hasHeightForWidth())
        self.spinBox_133.setSizePolicy(sizePolicy1)
        self.spinBox_133.setMinimumSize(QSize(100, 0))
        self.spinBox_133.setMaximumSize(QSize(120, 16777215))
        self.splitter_380.addWidget(self.spinBox_133)

        self.gridLayout.addWidget(self.splitter_380, 9, 0, 1, 1)

        self.splitter_382 = QSplitter(self.groupBox_19)
        self.splitter_382.setObjectName(u"splitter_382")
        self.splitter_382.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_382.setHandleWidth(0)
        self.label_194 = QLabel(self.splitter_382)
        self.label_194.setObjectName(u"label_194")
        self.splitter_382.addWidget(self.label_194)
        self.spinBox_135 = QSpinBox(self.splitter_382)
        self.spinBox_135.setObjectName(u"spinBox_135")
        sizePolicy1.setHeightForWidth(self.spinBox_135.sizePolicy().hasHeightForWidth())
        self.spinBox_135.setSizePolicy(sizePolicy1)
        self.spinBox_135.setMinimumSize(QSize(100, 0))
        self.spinBox_135.setMaximumSize(QSize(120, 16777215))
        self.splitter_382.addWidget(self.spinBox_135)

        self.gridLayout.addWidget(self.splitter_382, 10, 0, 1, 1)

        self.pushButton_292 = QPushButton(self.groupBox_19)
        self.pushButton_292.setObjectName(u"pushButton_292")

        self.gridLayout.addWidget(self.pushButton_292, 11, 0, 1, 1)


        self.gridLayout_2.addWidget(self.groupBox_19, 7, 0, 1, 1)

        self.splitter_3 = QSplitter(self.frame)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Orientation.Vertical)
        self.splitter_3.setHandleWidth(0)
        self.splitter_368 = QSplitter(self.splitter_3)
        self.splitter_368.setObjectName(u"splitter_368")
        self.splitter_368.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_368.setHandleWidth(0)
        self.pushButton_286 = QPushButton(self.splitter_368)
        self.pushButton_286.setObjectName(u"pushButton_286")
        self.splitter_368.addWidget(self.pushButton_286)
        self.pushButton_287 = QPushButton(self.splitter_368)
        self.pushButton_287.setObjectName(u"pushButton_287")
        self.splitter_368.addWidget(self.pushButton_287)
        self.splitter_3.addWidget(self.splitter_368)
        self.splitter_369 = QSplitter(self.splitter_3)
        self.splitter_369.setObjectName(u"splitter_369")
        self.splitter_369.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_369.setHandleWidth(0)
        self.pushButton_288 = QPushButton(self.splitter_369)
        self.pushButton_288.setObjectName(u"pushButton_288")
        self.splitter_369.addWidget(self.pushButton_288)
        self.pushButton_289 = QPushButton(self.splitter_369)
        self.pushButton_289.setObjectName(u"pushButton_289")
        self.splitter_369.addWidget(self.pushButton_289)
        self.splitter_3.addWidget(self.splitter_369)
        self.splitter_371 = QSplitter(self.splitter_3)
        self.splitter_371.setObjectName(u"splitter_371")
        self.splitter_371.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_371.setHandleWidth(0)
        self.pushButton_290 = QPushButton(self.splitter_371)
        self.pushButton_290.setObjectName(u"pushButton_290")
        self.splitter_371.addWidget(self.pushButton_290)
        self.pushButton_291 = QPushButton(self.splitter_371)
        self.pushButton_291.setObjectName(u"pushButton_291")
        self.splitter_371.addWidget(self.pushButton_291)
        self.splitter_3.addWidget(self.splitter_371)

        self.gridLayout_2.addWidget(self.splitter_3, 5, 0, 1, 1)

        self.label_184 = QLabel(self.frame)
        self.label_184.setObjectName(u"label_184")
        self.label_184.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_184, 3, 0, 1, 1)


        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)


        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label_185.setText(QCoreApplication.translate("Form", u"setings", None))
        self.pushButton_282.setText(QCoreApplication.translate("Form", u"Campfire ", None))
        self.pushButton_283.setText(QCoreApplication.translate("Form", u"Torch ", None))
        self.pushButton_284.setText(QCoreApplication.translate("Form", u"Candle ", None))
        self.pushButton_285.setText(QCoreApplication.translate("Form", u"Lava ", None))
        self.label_183.setText(QCoreApplication.translate("Form", u"fire", None))
        self.pushButton_281.setText(QCoreApplication.translate("Form", u"X", None))
        self.groupBox_19.setTitle("")
        self.label_195.setText(QCoreApplication.translate("Form", u"flame size", None))
        self.label_188.setText(QCoreApplication.translate("Form", u"intensity ", None))
        self.label_187.setText(QCoreApplication.translate("Form", u"flicker speed", None))
        self.label_186.setText(QCoreApplication.translate("Form", u"randomness        ", None))
        self.label_196.setText(QCoreApplication.translate("Form", u"grain             ", None))
        self.label_193.setText(QCoreApplication.translate("Form", u"opacity", None))
        self.label_189.setText(QCoreApplication.translate("Form", u"spark count", None))
        self.label_190.setText(QCoreApplication.translate("Form", u"distortion strength", None))
        self.label_191.setText(QCoreApplication.translate("Form", u"glow pulse", None))
        self.label_192.setText(QCoreApplication.translate("Form", u"light radius", None))
        self.label_194.setText(QCoreApplication.translate("Form", u"smoke length", None))
        self.pushButton_292.setText(QCoreApplication.translate("Form", u"color", None))
        self.pushButton_286.setText(QCoreApplication.translate("Form", u"sparks", None))
        self.pushButton_287.setText(QCoreApplication.translate("Form", u"smoke", None))
        self.pushButton_288.setText(QCoreApplication.translate("Form", u"heat distortion", None))
        self.pushButton_289.setText(QCoreApplication.translate("Form", u"pulse", None))
        self.pushButton_290.setText(QCoreApplication.translate("Form", u"shadow flicker", None))
        self.pushButton_291.setText(QCoreApplication.translate("Form", u"light glow", None))
        self.label_184.setText(QCoreApplication.translate("Form", u"sub functions", None))
    # retranslateUi

