# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'fire_tool.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGridLayout,
    QGroupBox, QLabel, QPushButton, QSizePolicy,
    QSplitter, QWidget)

class Ui_fire_tool(object):
    def setupUi(self, fire_tool):
        if not fire_tool.objectName():
            fire_tool.setObjectName(u"fire_tool")
        fire_tool.resize(280, 594)
        fire_tool.setMaximumSize(QSize(280, 16777215))
        self.gridLayout_3 = QGridLayout(fire_tool)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.frame = QFrame(fire_tool)
        self.frame.setObjectName(u"frame")
        self.frame.setEnabled(True)
        self.frame.setMaximumSize(QSize(280, 16777215))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_2 = QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.label_185 = QLabel(self.frame)
        self.label_185.setObjectName(u"label_185")
        self.label_185.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_185, 6, 0, 1, 1)

        self.splitter_2 = QSplitter(self.frame)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_2.setHandleWidth(0)
        self.main_Campfire = QPushButton(self.splitter_2)
        self.main_Campfire.setObjectName(u"main_Campfire")
        self.splitter_2.addWidget(self.main_Campfire)
        self.main_Torch = QPushButton(self.splitter_2)
        self.main_Torch.setObjectName(u"main_Torch")
        self.splitter_2.addWidget(self.main_Torch)
        self.main_Candle = QPushButton(self.splitter_2)
        self.main_Candle.setObjectName(u"main_Candle")
        self.splitter_2.addWidget(self.main_Candle)
        self.main_Lava = QPushButton(self.splitter_2)
        self.main_Lava.setObjectName(u"main_Lava")
        self.splitter_2.addWidget(self.main_Lava)

        self.gridLayout_2.addWidget(self.splitter_2, 2, 0, 1, 1)

        self.splitter = QSplitter(self.frame)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(0)
        self.label_183 = QLabel(self.splitter)
        self.label_183.setObjectName(u"label_183")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_183.sizePolicy().hasHeightForWidth())
        self.label_183.setSizePolicy(sizePolicy)
        self.label_183.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter.addWidget(self.label_183)
        self.pushButton_281 = QPushButton(self.splitter)
        self.pushButton_281.setObjectName(u"pushButton_281")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pushButton_281.sizePolicy().hasHeightForWidth())
        self.pushButton_281.setSizePolicy(sizePolicy1)
        self.pushButton_281.setMaximumSize(QSize(30, 30))
        self.splitter.addWidget(self.pushButton_281)

        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 1)

        self.groupBox_19 = QGroupBox(self.frame)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.gridLayout = QGridLayout(self.groupBox_19)
        self.gridLayout.setObjectName(u"gridLayout")
        self.splitter_383 = QSplitter(self.groupBox_19)
        self.splitter_383.setObjectName(u"splitter_383")
        self.splitter_383.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_383.setHandleWidth(0)
        self.label_195 = QLabel(self.splitter_383)
        self.label_195.setObjectName(u"label_195")
        self.splitter_383.addWidget(self.label_195)
        self.comboBox_6 = QComboBox(self.splitter_383)
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.splitter_383.addWidget(self.comboBox_6)

        self.gridLayout.addWidget(self.splitter_383, 0, 0, 1, 1)

        self.splitter_376 = QSplitter(self.groupBox_19)
        self.splitter_376.setObjectName(u"splitter_376")
        self.splitter_376.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_376.setHandleWidth(0)
        self.label_188 = QLabel(self.splitter_376)
        self.label_188.setObjectName(u"label_188")
        self.splitter_376.addWidget(self.label_188)
        self.comboBox_12 = QComboBox(self.splitter_376)
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.setObjectName(u"comboBox_12")
        self.splitter_376.addWidget(self.comboBox_12)

        self.gridLayout.addWidget(self.splitter_376, 1, 0, 1, 1)

        self.splitter_375 = QSplitter(self.groupBox_19)
        self.splitter_375.setObjectName(u"splitter_375")
        self.splitter_375.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_375.setHandleWidth(0)
        self.label_187 = QLabel(self.splitter_375)
        self.label_187.setObjectName(u"label_187")
        self.splitter_375.addWidget(self.label_187)
        self.comboBox_11 = QComboBox(self.splitter_375)
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.setObjectName(u"comboBox_11")
        self.splitter_375.addWidget(self.comboBox_11)

        self.gridLayout.addWidget(self.splitter_375, 2, 0, 1, 1)

        self.splitter_374 = QSplitter(self.groupBox_19)
        self.splitter_374.setObjectName(u"splitter_374")
        self.splitter_374.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_374.setHandleWidth(0)
        self.label_186 = QLabel(self.splitter_374)
        self.label_186.setObjectName(u"label_186")
        self.splitter_374.addWidget(self.label_186)
        self.comboBox_10 = QComboBox(self.splitter_374)
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.setObjectName(u"comboBox_10")
        self.splitter_374.addWidget(self.comboBox_10)

        self.gridLayout.addWidget(self.splitter_374, 3, 0, 1, 1)

        self.splitter_384 = QSplitter(self.groupBox_19)
        self.splitter_384.setObjectName(u"splitter_384")
        self.splitter_384.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_384.setHandleWidth(0)
        self.label_196 = QLabel(self.splitter_384)
        self.label_196.setObjectName(u"label_196")
        self.splitter_384.addWidget(self.label_196)
        self.comboBox_9 = QComboBox(self.splitter_384)
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.setObjectName(u"comboBox_9")
        self.splitter_384.addWidget(self.comboBox_9)

        self.gridLayout.addWidget(self.splitter_384, 4, 0, 1, 1)

        self.splitter_381 = QSplitter(self.groupBox_19)
        self.splitter_381.setObjectName(u"splitter_381")
        self.splitter_381.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_381.setHandleWidth(0)
        self.label_193 = QLabel(self.splitter_381)
        self.label_193.setObjectName(u"label_193")
        self.splitter_381.addWidget(self.label_193)
        self.comboBox_8 = QComboBox(self.splitter_381)
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.setObjectName(u"comboBox_8")
        self.splitter_381.addWidget(self.comboBox_8)

        self.gridLayout.addWidget(self.splitter_381, 5, 0, 1, 1)

        self.splitter_377 = QSplitter(self.groupBox_19)
        self.splitter_377.setObjectName(u"splitter_377")
        self.splitter_377.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_377.setHandleWidth(0)
        self.label_189 = QLabel(self.splitter_377)
        self.label_189.setObjectName(u"label_189")
        self.splitter_377.addWidget(self.label_189)
        self.comboBox_7 = QComboBox(self.splitter_377)
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.setObjectName(u"comboBox_7")
        self.splitter_377.addWidget(self.comboBox_7)

        self.gridLayout.addWidget(self.splitter_377, 6, 0, 1, 1)

        self.splitter_378 = QSplitter(self.groupBox_19)
        self.splitter_378.setObjectName(u"splitter_378")
        self.splitter_378.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_378.setHandleWidth(0)
        self.label_190 = QLabel(self.splitter_378)
        self.label_190.setObjectName(u"label_190")
        self.splitter_378.addWidget(self.label_190)
        self.comboBox_5 = QComboBox(self.splitter_378)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.splitter_378.addWidget(self.comboBox_5)

        self.gridLayout.addWidget(self.splitter_378, 7, 0, 1, 1)

        self.splitter_379 = QSplitter(self.groupBox_19)
        self.splitter_379.setObjectName(u"splitter_379")
        self.splitter_379.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_379.setHandleWidth(0)
        self.label_191 = QLabel(self.splitter_379)
        self.label_191.setObjectName(u"label_191")
        self.splitter_379.addWidget(self.label_191)
        self.comboBox_13 = QComboBox(self.splitter_379)
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.setObjectName(u"comboBox_13")
        self.splitter_379.addWidget(self.comboBox_13)

        self.gridLayout.addWidget(self.splitter_379, 8, 0, 1, 1)

        self.splitter_380 = QSplitter(self.groupBox_19)
        self.splitter_380.setObjectName(u"splitter_380")
        self.splitter_380.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_380.setHandleWidth(0)
        self.label_192 = QLabel(self.splitter_380)
        self.label_192.setObjectName(u"label_192")
        self.splitter_380.addWidget(self.label_192)
        self.comboBox_14 = QComboBox(self.splitter_380)
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.setObjectName(u"comboBox_14")
        self.splitter_380.addWidget(self.comboBox_14)

        self.gridLayout.addWidget(self.splitter_380, 9, 0, 1, 1)

        self.splitter_382 = QSplitter(self.groupBox_19)
        self.splitter_382.setObjectName(u"splitter_382")
        self.splitter_382.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_382.setHandleWidth(0)
        self.label_194 = QLabel(self.splitter_382)
        self.label_194.setObjectName(u"label_194")
        self.splitter_382.addWidget(self.label_194)
        self.comboBox_15 = QComboBox(self.splitter_382)
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.setObjectName(u"comboBox_15")
        self.splitter_382.addWidget(self.comboBox_15)

        self.gridLayout.addWidget(self.splitter_382, 10, 0, 1, 1)

        self.pushButton_292 = QPushButton(self.groupBox_19)
        self.pushButton_292.setObjectName(u"pushButton_292")

        self.gridLayout.addWidget(self.pushButton_292, 11, 0, 1, 1)


        self.gridLayout_2.addWidget(self.groupBox_19, 7, 0, 1, 1)

        self.splitter_3 = QSplitter(self.frame)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Orientation.Vertical)
        self.splitter_3.setHandleWidth(0)
        self.splitter_368 = QSplitter(self.splitter_3)
        self.splitter_368.setObjectName(u"splitter_368")
        self.splitter_368.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_368.setHandleWidth(0)
        self.sub_sparks = QPushButton(self.splitter_368)
        self.sub_sparks.setObjectName(u"sub_sparks")
        self.splitter_368.addWidget(self.sub_sparks)
        self.sub_smoke = QPushButton(self.splitter_368)
        self.sub_smoke.setObjectName(u"sub_smoke")
        self.splitter_368.addWidget(self.sub_smoke)
        self.splitter_3.addWidget(self.splitter_368)
        self.splitter_369 = QSplitter(self.splitter_3)
        self.splitter_369.setObjectName(u"splitter_369")
        self.splitter_369.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_369.setHandleWidth(0)
        self.sub_heat_distortion = QPushButton(self.splitter_369)
        self.sub_heat_distortion.setObjectName(u"sub_heat_distortion")
        self.splitter_369.addWidget(self.sub_heat_distortion)
        self.sub_pulse = QPushButton(self.splitter_369)
        self.sub_pulse.setObjectName(u"sub_pulse")
        self.splitter_369.addWidget(self.sub_pulse)
        self.splitter_3.addWidget(self.splitter_369)
        self.splitter_371 = QSplitter(self.splitter_3)
        self.splitter_371.setObjectName(u"splitter_371")
        self.splitter_371.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_371.setHandleWidth(0)
        self.sub_shadow_flicker = QPushButton(self.splitter_371)
        self.sub_shadow_flicker.setObjectName(u"sub_shadow_flicker")
        self.splitter_371.addWidget(self.sub_shadow_flicker)
        self.sub_light_glow = QPushButton(self.splitter_371)
        self.sub_light_glow.setObjectName(u"sub_light_glow")
        self.splitter_371.addWidget(self.sub_light_glow)
        self.splitter_3.addWidget(self.splitter_371)

        self.gridLayout_2.addWidget(self.splitter_3, 5, 0, 1, 1)

        self.label_184 = QLabel(self.frame)
        self.label_184.setObjectName(u"label_184")
        self.label_184.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_184, 3, 0, 1, 1)


        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)


        self.retranslateUi(fire_tool)

        QMetaObject.connectSlotsByName(fire_tool)
    # setupUi

    def retranslateUi(self, fire_tool):
        fire_tool.setWindowTitle(QCoreApplication.translate("fire_tool", u"Form", None))
        self.label_185.setText(QCoreApplication.translate("fire_tool", u"setings", None))
        self.main_Campfire.setText(QCoreApplication.translate("fire_tool", u"Campfire ", None))
        self.main_Torch.setText(QCoreApplication.translate("fire_tool", u"Torch ", None))
        self.main_Candle.setText(QCoreApplication.translate("fire_tool", u"Candle ", None))
        self.main_Lava.setText(QCoreApplication.translate("fire_tool", u"Lava ", None))
        self.label_183.setText(QCoreApplication.translate("fire_tool", u"fire", None))
        self.pushButton_281.setText(QCoreApplication.translate("fire_tool", u"X", None))
        self.groupBox_19.setTitle("")
        self.label_195.setText(QCoreApplication.translate("fire_tool", u"flame size", None))
        self.comboBox_6.setItemText(0, QCoreApplication.translate("fire_tool", u"weak", None))
        self.comboBox_6.setItemText(1, QCoreApplication.translate("fire_tool", u"strong", None))
        self.comboBox_6.setItemText(2, QCoreApplication.translate("fire_tool", u"normal", None))

        self.label_188.setText(QCoreApplication.translate("fire_tool", u"intensity ", None))
        self.comboBox_12.setItemText(0, QCoreApplication.translate("fire_tool", u"weak", None))
        self.comboBox_12.setItemText(1, QCoreApplication.translate("fire_tool", u"strong", None))
        self.comboBox_12.setItemText(2, QCoreApplication.translate("fire_tool", u"normal", None))

        self.label_187.setText(QCoreApplication.translate("fire_tool", u"flicker speed", None))
        self.comboBox_11.setItemText(0, QCoreApplication.translate("fire_tool", u"weak", None))
        self.comboBox_11.setItemText(1, QCoreApplication.translate("fire_tool", u"strong", None))
        self.comboBox_11.setItemText(2, QCoreApplication.translate("fire_tool", u"normal", None))

        self.label_186.setText(QCoreApplication.translate("fire_tool", u"randomness        ", None))
        self.comboBox_10.setItemText(0, QCoreApplication.translate("fire_tool", u"weak", None))
        self.comboBox_10.setItemText(1, QCoreApplication.translate("fire_tool", u"strong", None))
        self.comboBox_10.setItemText(2, QCoreApplication.translate("fire_tool", u"normal", None))

        self.label_196.setText(QCoreApplication.translate("fire_tool", u"grain             ", None))
        self.comboBox_9.setItemText(0, QCoreApplication.translate("fire_tool", u"weak", None))
        self.comboBox_9.setItemText(1, QCoreApplication.translate("fire_tool", u"strong", None))
        self.comboBox_9.setItemText(2, QCoreApplication.translate("fire_tool", u"normal", None))

        self.label_193.setText(QCoreApplication.translate("fire_tool", u"opacity", None))
        self.comboBox_8.setItemText(0, QCoreApplication.translate("fire_tool", u"weak", None))
        self.comboBox_8.setItemText(1, QCoreApplication.translate("fire_tool", u"strong", None))
        self.comboBox_8.setItemText(2, QCoreApplication.translate("fire_tool", u"normal", None))

        self.label_189.setText(QCoreApplication.translate("fire_tool", u"spark count", None))
        self.comboBox_7.setItemText(0, QCoreApplication.translate("fire_tool", u"weak", None))
        self.comboBox_7.setItemText(1, QCoreApplication.translate("fire_tool", u"strong", None))
        self.comboBox_7.setItemText(2, QCoreApplication.translate("fire_tool", u"normal", None))

        self.label_190.setText(QCoreApplication.translate("fire_tool", u"distortion strength", None))
        self.comboBox_5.setItemText(0, QCoreApplication.translate("fire_tool", u"weak", None))
        self.comboBox_5.setItemText(1, QCoreApplication.translate("fire_tool", u"strong", None))
        self.comboBox_5.setItemText(2, QCoreApplication.translate("fire_tool", u"normal", None))

        self.label_191.setText(QCoreApplication.translate("fire_tool", u"glow pulse", None))
        self.comboBox_13.setItemText(0, QCoreApplication.translate("fire_tool", u"weak", None))
        self.comboBox_13.setItemText(1, QCoreApplication.translate("fire_tool", u"strong", None))
        self.comboBox_13.setItemText(2, QCoreApplication.translate("fire_tool", u"normal", None))

        self.label_192.setText(QCoreApplication.translate("fire_tool", u"light radius", None))
        self.comboBox_14.setItemText(0, QCoreApplication.translate("fire_tool", u"weak", None))
        self.comboBox_14.setItemText(1, QCoreApplication.translate("fire_tool", u"strong", None))
        self.comboBox_14.setItemText(2, QCoreApplication.translate("fire_tool", u"normal", None))

        self.label_194.setText(QCoreApplication.translate("fire_tool", u"smoke length", None))
        self.comboBox_15.setItemText(0, QCoreApplication.translate("fire_tool", u"weak", None))
        self.comboBox_15.setItemText(1, QCoreApplication.translate("fire_tool", u"strong", None))
        self.comboBox_15.setItemText(2, QCoreApplication.translate("fire_tool", u"normal", None))

        self.pushButton_292.setText(QCoreApplication.translate("fire_tool", u"color", None))
        self.sub_sparks.setText(QCoreApplication.translate("fire_tool", u"sparks", None))
        self.sub_smoke.setText(QCoreApplication.translate("fire_tool", u"smoke", None))
        self.sub_heat_distortion.setText(QCoreApplication.translate("fire_tool", u"heat distortion", None))
        self.sub_pulse.setText(QCoreApplication.translate("fire_tool", u"pulse", None))
        self.sub_shadow_flicker.setText(QCoreApplication.translate("fire_tool", u"shadow flicker", None))
        self.sub_light_glow.setText(QCoreApplication.translate("fire_tool", u"light glow", None))
        self.label_184.setText(QCoreApplication.translate("fire_tool", u"sub functions", None))
    # retranslateUi

