# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'light_tool.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QGroupBox,
    QHBoxLayout, QLabel, QPushButton, QRadioButton,
    QSizePolicy, QSpinBox, QSplitter, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(280, 620)
        Form.setMaximumSize(QSize(280, 16777215))
        self.horizontalLayout = QHBoxLayout(Form)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QSize(280, 16777215))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout = QGridLayout(self.frame)
        self.gridLayout.setObjectName(u"gridLayout")
        self.splitter_3 = QSplitter(self.frame)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Orientation.Vertical)
        self.splitter_3.setHandleWidth(0)
        self.splitter = QSplitter(self.splitter_3)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(0)
        self.label_168 = QLabel(self.splitter)
        self.label_168.setObjectName(u"label_168")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_168.sizePolicy().hasHeightForWidth())
        self.label_168.setSizePolicy(sizePolicy1)
        self.label_168.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter.addWidget(self.label_168)
        self.pushButton_293 = QPushButton(self.splitter)
        self.pushButton_293.setObjectName(u"pushButton_293")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pushButton_293.sizePolicy().hasHeightForWidth())
        self.pushButton_293.setSizePolicy(sizePolicy2)
        self.pushButton_293.setMaximumSize(QSize(30, 30))
        self.splitter.addWidget(self.pushButton_293)
        self.splitter_3.addWidget(self.splitter)
        self.splitter_2 = QSplitter(self.splitter_3)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_2.setHandleWidth(0)
        self.pushButton_294 = QPushButton(self.splitter_2)
        self.pushButton_294.setObjectName(u"pushButton_294")
        self.splitter_2.addWidget(self.pushButton_294)
        self.pushButton_296 = QPushButton(self.splitter_2)
        self.pushButton_296.setObjectName(u"pushButton_296")
        self.splitter_2.addWidget(self.pushButton_296)
        self.pushButton_297 = QPushButton(self.splitter_2)
        self.pushButton_297.setObjectName(u"pushButton_297")
        self.splitter_2.addWidget(self.pushButton_297)
        self.splitter_3.addWidget(self.splitter_2)
        self.label_172 = QLabel(self.splitter_3)
        self.label_172.setObjectName(u"label_172")
        self.label_172.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter_3.addWidget(self.label_172)
        self.splitter_390 = QSplitter(self.splitter_3)
        self.splitter_390.setObjectName(u"splitter_390")
        self.splitter_390.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_390.setHandleWidth(0)
        self.pushButton_298 = QPushButton(self.splitter_390)
        self.pushButton_298.setObjectName(u"pushButton_298")
        self.splitter_390.addWidget(self.pushButton_298)
        self.pushButton_299 = QPushButton(self.splitter_390)
        self.pushButton_299.setObjectName(u"pushButton_299")
        self.splitter_390.addWidget(self.pushButton_299)
        self.pushButton = QPushButton(self.splitter_390)
        self.pushButton.setObjectName(u"pushButton")
        self.splitter_390.addWidget(self.pushButton)
        self.splitter_3.addWidget(self.splitter_390)
        self.splitter_391 = QSplitter(self.splitter_3)
        self.splitter_391.setObjectName(u"splitter_391")
        self.splitter_391.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_391.setHandleWidth(0)
        self.pushButton_300 = QPushButton(self.splitter_391)
        self.pushButton_300.setObjectName(u"pushButton_300")
        self.splitter_391.addWidget(self.pushButton_300)
        self.pushButton_301 = QPushButton(self.splitter_391)
        self.pushButton_301.setObjectName(u"pushButton_301")
        self.splitter_391.addWidget(self.pushButton_301)
        self.pushButton_2 = QPushButton(self.splitter_391)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.splitter_391.addWidget(self.pushButton_2)
        self.splitter_3.addWidget(self.splitter_391)
        self.splitter_393 = QSplitter(self.splitter_3)
        self.splitter_393.setObjectName(u"splitter_393")
        self.splitter_393.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_393.setHandleWidth(0)
        self.pushButton_302 = QPushButton(self.splitter_393)
        self.pushButton_302.setObjectName(u"pushButton_302")
        self.splitter_393.addWidget(self.pushButton_302)
        self.pushButton_303 = QPushButton(self.splitter_393)
        self.pushButton_303.setObjectName(u"pushButton_303")
        self.splitter_393.addWidget(self.pushButton_303)
        self.pushButton_3 = QPushButton(self.splitter_393)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.splitter_393.addWidget(self.pushButton_3)
        self.splitter_3.addWidget(self.splitter_393)
        self.splitter_395 = QSplitter(self.splitter_3)
        self.splitter_395.setObjectName(u"splitter_395")
        self.splitter_395.setOrientation(Qt.Orientation.Vertical)
        self.splitter_395.setHandleWidth(0)
        self.label_197 = QLabel(self.splitter_395)
        self.label_197.setObjectName(u"label_197")
        self.label_197.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter_395.addWidget(self.label_197)
        self.groupBox_20 = QGroupBox(self.splitter_395)
        self.groupBox_20.setObjectName(u"groupBox_20")
        self.groupBox_20.setMaximumSize(QSize(280, 16777215))
        self.gridLayout_3 = QGridLayout(self.groupBox_20)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.splitter_396 = QSplitter(self.groupBox_20)
        self.splitter_396.setObjectName(u"splitter_396")
        self.splitter_396.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_396.setHandleWidth(0)
        self.label_198 = QLabel(self.splitter_396)
        self.label_198.setObjectName(u"label_198")
        self.splitter_396.addWidget(self.label_198)
        self.spinBox_138 = QSpinBox(self.splitter_396)
        self.spinBox_138.setObjectName(u"spinBox_138")
        self.splitter_396.addWidget(self.spinBox_138)

        self.gridLayout_3.addWidget(self.splitter_396, 0, 0, 1, 1)

        self.splitter_401 = QSplitter(self.groupBox_20)
        self.splitter_401.setObjectName(u"splitter_401")
        self.splitter_401.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_401.setHandleWidth(0)
        self.label_203 = QLabel(self.splitter_401)
        self.label_203.setObjectName(u"label_203")
        self.splitter_401.addWidget(self.label_203)
        self.spinBox_141 = QSpinBox(self.splitter_401)
        self.spinBox_141.setObjectName(u"spinBox_141")
        self.splitter_401.addWidget(self.spinBox_141)

        self.gridLayout_3.addWidget(self.splitter_401, 1, 0, 1, 1)

        self.splitter_404 = QSplitter(self.groupBox_20)
        self.splitter_404.setObjectName(u"splitter_404")
        self.splitter_404.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_404.setHandleWidth(0)
        self.label_206 = QLabel(self.splitter_404)
        self.label_206.setObjectName(u"label_206")
        self.splitter_404.addWidget(self.label_206)
        self.spinBox_144 = QSpinBox(self.splitter_404)
        self.spinBox_144.setObjectName(u"spinBox_144")
        self.splitter_404.addWidget(self.spinBox_144)

        self.gridLayout_3.addWidget(self.splitter_404, 2, 0, 1, 1)

        self.splitter_400 = QSplitter(self.groupBox_20)
        self.splitter_400.setObjectName(u"splitter_400")
        self.splitter_400.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_400.setHandleWidth(0)
        self.label_202 = QLabel(self.splitter_400)
        self.label_202.setObjectName(u"label_202")
        self.splitter_400.addWidget(self.label_202)
        self.spinBox_140 = QSpinBox(self.splitter_400)
        self.spinBox_140.setObjectName(u"spinBox_140")
        sizePolicy2.setHeightForWidth(self.spinBox_140.sizePolicy().hasHeightForWidth())
        self.spinBox_140.setSizePolicy(sizePolicy2)
        self.spinBox_140.setMinimumSize(QSize(100, 0))
        self.spinBox_140.setMaximumSize(QSize(120, 16777215))
        self.splitter_400.addWidget(self.spinBox_140)

        self.gridLayout_3.addWidget(self.splitter_400, 3, 0, 1, 1)

        self.splitter_398 = QSplitter(self.groupBox_20)
        self.splitter_398.setObjectName(u"splitter_398")
        self.splitter_398.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_398.setHandleWidth(0)
        self.label_200 = QLabel(self.splitter_398)
        self.label_200.setObjectName(u"label_200")
        self.splitter_398.addWidget(self.label_200)
        self.spinBox_119 = QSpinBox(self.splitter_398)
        self.spinBox_119.setObjectName(u"spinBox_119")
        sizePolicy2.setHeightForWidth(self.spinBox_119.sizePolicy().hasHeightForWidth())
        self.spinBox_119.setSizePolicy(sizePolicy2)
        self.spinBox_119.setMinimumSize(QSize(100, 0))
        self.spinBox_119.setMaximumSize(QSize(120, 16777215))
        self.splitter_398.addWidget(self.spinBox_119)

        self.gridLayout_3.addWidget(self.splitter_398, 4, 0, 1, 1)

        self.splitter_402 = QSplitter(self.groupBox_20)
        self.splitter_402.setObjectName(u"splitter_402")
        self.splitter_402.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_402.setHandleWidth(0)
        self.label_204 = QLabel(self.splitter_402)
        self.label_204.setObjectName(u"label_204")
        self.splitter_402.addWidget(self.label_204)
        self.spinBox_142 = QSpinBox(self.splitter_402)
        self.spinBox_142.setObjectName(u"spinBox_142")
        sizePolicy2.setHeightForWidth(self.spinBox_142.sizePolicy().hasHeightForWidth())
        self.spinBox_142.setSizePolicy(sizePolicy2)
        self.spinBox_142.setMinimumSize(QSize(100, 0))
        self.spinBox_142.setMaximumSize(QSize(120, 16777215))
        self.splitter_402.addWidget(self.spinBox_142)

        self.gridLayout_3.addWidget(self.splitter_402, 5, 0, 1, 1)

        self.splitter_399 = QSplitter(self.groupBox_20)
        self.splitter_399.setObjectName(u"splitter_399")
        self.splitter_399.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_399.setHandleWidth(0)
        self.label_201 = QLabel(self.splitter_399)
        self.label_201.setObjectName(u"label_201")
        self.splitter_399.addWidget(self.label_201)
        self.spinBox_139 = QSpinBox(self.splitter_399)
        self.spinBox_139.setObjectName(u"spinBox_139")
        sizePolicy2.setHeightForWidth(self.spinBox_139.sizePolicy().hasHeightForWidth())
        self.spinBox_139.setSizePolicy(sizePolicy2)
        self.spinBox_139.setMinimumSize(QSize(100, 0))
        self.spinBox_139.setMaximumSize(QSize(120, 16777215))
        self.splitter_399.addWidget(self.spinBox_139)

        self.gridLayout_3.addWidget(self.splitter_399, 6, 0, 1, 1)

        self.splitter_397 = QSplitter(self.groupBox_20)
        self.splitter_397.setObjectName(u"splitter_397")
        self.splitter_397.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_397.setHandleWidth(0)
        self.label_199 = QLabel(self.splitter_397)
        self.label_199.setObjectName(u"label_199")
        self.splitter_397.addWidget(self.label_199)
        self.spinBox_115 = QSpinBox(self.splitter_397)
        self.spinBox_115.setObjectName(u"spinBox_115")
        sizePolicy2.setHeightForWidth(self.spinBox_115.sizePolicy().hasHeightForWidth())
        self.spinBox_115.setSizePolicy(sizePolicy2)
        self.spinBox_115.setMinimumSize(QSize(100, 0))
        self.spinBox_115.setMaximumSize(QSize(120, 16777215))
        self.splitter_397.addWidget(self.spinBox_115)

        self.gridLayout_3.addWidget(self.splitter_397, 7, 0, 1, 1)

        self.splitter_403 = QSplitter(self.groupBox_20)
        self.splitter_403.setObjectName(u"splitter_403")
        self.splitter_403.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_403.setHandleWidth(0)
        self.label_205 = QLabel(self.splitter_403)
        self.label_205.setObjectName(u"label_205")
        self.splitter_403.addWidget(self.label_205)
        self.spinBox_143 = QSpinBox(self.splitter_403)
        self.spinBox_143.setObjectName(u"spinBox_143")
        sizePolicy2.setHeightForWidth(self.spinBox_143.sizePolicy().hasHeightForWidth())
        self.spinBox_143.setSizePolicy(sizePolicy2)
        self.spinBox_143.setMinimumSize(QSize(100, 0))
        self.spinBox_143.setMaximumSize(QSize(120, 16777215))
        self.splitter_403.addWidget(self.spinBox_143)

        self.gridLayout_3.addWidget(self.splitter_403, 8, 0, 1, 1)

        self.splitter_407 = QSplitter(self.groupBox_20)
        self.splitter_407.setObjectName(u"splitter_407")
        self.splitter_407.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_407.setHandleWidth(0)
        self.label_209 = QLabel(self.splitter_407)
        self.label_209.setObjectName(u"label_209")
        self.splitter_407.addWidget(self.label_209)
        self.spinBox_147 = QSpinBox(self.splitter_407)
        self.spinBox_147.setObjectName(u"spinBox_147")
        sizePolicy2.setHeightForWidth(self.spinBox_147.sizePolicy().hasHeightForWidth())
        self.spinBox_147.setSizePolicy(sizePolicy2)
        self.spinBox_147.setMinimumSize(QSize(100, 0))
        self.spinBox_147.setMaximumSize(QSize(120, 16777215))
        self.splitter_407.addWidget(self.spinBox_147)

        self.gridLayout_3.addWidget(self.splitter_407, 9, 0, 1, 1)

        self.splitter_406 = QSplitter(self.groupBox_20)
        self.splitter_406.setObjectName(u"splitter_406")
        self.splitter_406.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_406.setHandleWidth(0)
        self.label_208 = QLabel(self.splitter_406)
        self.label_208.setObjectName(u"label_208")
        self.splitter_406.addWidget(self.label_208)
        self.spinBox_146 = QSpinBox(self.splitter_406)
        self.spinBox_146.setObjectName(u"spinBox_146")
        sizePolicy2.setHeightForWidth(self.spinBox_146.sizePolicy().hasHeightForWidth())
        self.spinBox_146.setSizePolicy(sizePolicy2)
        self.spinBox_146.setMinimumSize(QSize(100, 0))
        self.spinBox_146.setMaximumSize(QSize(120, 16777215))
        self.splitter_406.addWidget(self.spinBox_146)

        self.gridLayout_3.addWidget(self.splitter_406, 10, 0, 1, 1)

        self.splitter_405 = QSplitter(self.groupBox_20)
        self.splitter_405.setObjectName(u"splitter_405")
        self.splitter_405.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_405.setHandleWidth(0)
        self.label_207 = QLabel(self.splitter_405)
        self.label_207.setObjectName(u"label_207")
        self.splitter_405.addWidget(self.label_207)
        self.spinBox_145 = QSpinBox(self.splitter_405)
        self.spinBox_145.setObjectName(u"spinBox_145")
        sizePolicy2.setHeightForWidth(self.spinBox_145.sizePolicy().hasHeightForWidth())
        self.spinBox_145.setSizePolicy(sizePolicy2)
        self.spinBox_145.setMinimumSize(QSize(100, 0))
        self.spinBox_145.setMaximumSize(QSize(120, 16777215))
        self.splitter_405.addWidget(self.spinBox_145)

        self.gridLayout_3.addWidget(self.splitter_405, 11, 0, 1, 1)

        self.radioButton = QRadioButton(self.groupBox_20)
        self.radioButton.setObjectName(u"radioButton")

        self.gridLayout_3.addWidget(self.radioButton, 12, 0, 1, 1)

        self.pushButton_304 = QPushButton(self.groupBox_20)
        self.pushButton_304.setObjectName(u"pushButton_304")

        self.gridLayout_3.addWidget(self.pushButton_304, 13, 0, 1, 1)

        self.splitter_395.addWidget(self.groupBox_20)
        self.splitter_3.addWidget(self.splitter_395)

        self.gridLayout.addWidget(self.splitter_3, 0, 0, 1, 1)


        self.horizontalLayout.addWidget(self.frame)


        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label_168.setText(QCoreApplication.translate("Form", u"light", None))
        self.pushButton_293.setText(QCoreApplication.translate("Form", u"X", None))
        self.pushButton_294.setText(QCoreApplication.translate("Form", u"Firefly", None))
        self.pushButton_296.setText(QCoreApplication.translate("Form", u"Object Light", None))
        self.pushButton_297.setText(QCoreApplication.translate("Form", u"lightning", None))
        self.label_172.setText(QCoreApplication.translate("Form", u"sub functions", None))
        self.pushButton_298.setText(QCoreApplication.translate("Form", u"pulse", None))
        self.pushButton_299.setText(QCoreApplication.translate("Form", u"flicker", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"glow spread", None))
        self.pushButton_300.setText(QCoreApplication.translate("Form", u"trail", None))
        self.pushButton_301.setText(QCoreApplication.translate("Form", u"spark", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"flash", None))
        self.pushButton_302.setText(QCoreApplication.translate("Form", u"radius glow", None))
        self.pushButton_303.setText(QCoreApplication.translate("Form", u"focus pulse", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"branches", None))
        self.label_197.setText(QCoreApplication.translate("Form", u"setings", None))
        self.groupBox_20.setTitle("")
        self.label_198.setText(QCoreApplication.translate("Form", u"intensity", None))
        self.label_203.setText(QCoreApplication.translate("Form", u"radius", None))
        self.label_206.setText(QCoreApplication.translate("Form", u"pulse speed", None))
        self.label_202.setText(QCoreApplication.translate("Form", u"flicker frequency", None))
        self.label_200.setText(QCoreApplication.translate("Form", u"glow depth", None))
        self.label_204.setText(QCoreApplication.translate("Form", u"opacity", None))
        self.label_201.setText(QCoreApplication.translate("Form", u"count", None))
        self.label_199.setText(QCoreApplication.translate("Form", u"frequency", None))
        self.label_205.setText(QCoreApplication.translate("Form", u"duration   ", None))
        self.label_209.setText(QCoreApplication.translate("Form", u"branch count", None))
        self.label_208.setText(QCoreApplication.translate("Form", u"bolt width", None))
        self.label_207.setText(QCoreApplication.translate("Form", u"light radius ", None))
        self.radioButton.setText(QCoreApplication.translate("Form", u"sync with rain", None))
        self.pushButton_304.setText(QCoreApplication.translate("Form", u"color", None))
    # retranslateUi

