# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'light_tool.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGridLayout,
    QGroupBox, QHBoxLayout, QLabel, QPushButton,
    QRadioButton, QSizePolicy, QSplitter, QWidget)

class Ui_light_tool(object):
    def setupUi(self, light_tool):
        if not light_tool.objectName():
            light_tool.setObjectName(u"light_tool")
        light_tool.resize(280, 620)
        light_tool.setMaximumSize(QSize(280, 16777215))
        self.horizontalLayout = QHBoxLayout(light_tool)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.frame = QFrame(light_tool)
        self.frame.setObjectName(u"frame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QSize(280, 16777215))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout = QGridLayout(self.frame)
        self.gridLayout.setObjectName(u"gridLayout")
        self.splitter_3 = QSplitter(self.frame)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Orientation.Vertical)
        self.splitter_3.setHandleWidth(0)
        self.splitter = QSplitter(self.splitter_3)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(0)
        self.label_168 = QLabel(self.splitter)
        self.label_168.setObjectName(u"label_168")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_168.sizePolicy().hasHeightForWidth())
        self.label_168.setSizePolicy(sizePolicy1)
        self.label_168.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter.addWidget(self.label_168)
        self.pushButton_293 = QPushButton(self.splitter)
        self.pushButton_293.setObjectName(u"pushButton_293")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pushButton_293.sizePolicy().hasHeightForWidth())
        self.pushButton_293.setSizePolicy(sizePolicy2)
        self.pushButton_293.setMaximumSize(QSize(30, 30))
        self.splitter.addWidget(self.pushButton_293)
        self.splitter_3.addWidget(self.splitter)
        self.splitter_2 = QSplitter(self.splitter_3)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_2.setHandleWidth(0)
        self.main_Firefly = QPushButton(self.splitter_2)
        self.main_Firefly.setObjectName(u"main_Firefly")
        self.splitter_2.addWidget(self.main_Firefly)
        self.main_Object_Light = QPushButton(self.splitter_2)
        self.main_Object_Light.setObjectName(u"main_Object_Light")
        self.splitter_2.addWidget(self.main_Object_Light)
        self.main_lightning = QPushButton(self.splitter_2)
        self.main_lightning.setObjectName(u"main_lightning")
        self.splitter_2.addWidget(self.main_lightning)
        self.splitter_3.addWidget(self.splitter_2)
        self.label_172 = QLabel(self.splitter_3)
        self.label_172.setObjectName(u"label_172")
        self.label_172.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter_3.addWidget(self.label_172)
        self.splitter_390 = QSplitter(self.splitter_3)
        self.splitter_390.setObjectName(u"splitter_390")
        self.splitter_390.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_390.setHandleWidth(0)
        self.sub_pulse = QPushButton(self.splitter_390)
        self.sub_pulse.setObjectName(u"sub_pulse")
        self.splitter_390.addWidget(self.sub_pulse)
        self.sub_flicker = QPushButton(self.splitter_390)
        self.sub_flicker.setObjectName(u"sub_flicker")
        self.splitter_390.addWidget(self.sub_flicker)
        self.sub_glow_spread = QPushButton(self.splitter_390)
        self.sub_glow_spread.setObjectName(u"sub_glow_spread")
        self.splitter_390.addWidget(self.sub_glow_spread)
        self.splitter_3.addWidget(self.splitter_390)
        self.splitter_391 = QSplitter(self.splitter_3)
        self.splitter_391.setObjectName(u"splitter_391")
        self.splitter_391.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_391.setHandleWidth(0)
        self.sub_trail = QPushButton(self.splitter_391)
        self.sub_trail.setObjectName(u"sub_trail")
        self.splitter_391.addWidget(self.sub_trail)
        self.sub_spark = QPushButton(self.splitter_391)
        self.sub_spark.setObjectName(u"sub_spark")
        self.splitter_391.addWidget(self.sub_spark)
        self.sub_flash = QPushButton(self.splitter_391)
        self.sub_flash.setObjectName(u"sub_flash")
        self.splitter_391.addWidget(self.sub_flash)
        self.splitter_3.addWidget(self.splitter_391)
        self.splitter_393 = QSplitter(self.splitter_3)
        self.splitter_393.setObjectName(u"splitter_393")
        self.splitter_393.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_393.setHandleWidth(0)
        self.sub_radius_glow = QPushButton(self.splitter_393)
        self.sub_radius_glow.setObjectName(u"sub_radius_glow")
        self.splitter_393.addWidget(self.sub_radius_glow)
        self.sub_focus_pulse = QPushButton(self.splitter_393)
        self.sub_focus_pulse.setObjectName(u"sub_focus_pulse")
        self.splitter_393.addWidget(self.sub_focus_pulse)
        self.pushButton_3 = QPushButton(self.splitter_393)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.splitter_393.addWidget(self.pushButton_3)
        self.splitter_3.addWidget(self.splitter_393)
        self.splitter_395 = QSplitter(self.splitter_3)
        self.splitter_395.setObjectName(u"splitter_395")
        self.splitter_395.setOrientation(Qt.Orientation.Vertical)
        self.splitter_395.setHandleWidth(0)
        self.label_197 = QLabel(self.splitter_395)
        self.label_197.setObjectName(u"label_197")
        self.label_197.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter_395.addWidget(self.label_197)
        self.groupBox_20 = QGroupBox(self.splitter_395)
        self.groupBox_20.setObjectName(u"groupBox_20")
        self.groupBox_20.setMaximumSize(QSize(280, 16777215))
        self.gridLayout_3 = QGridLayout(self.groupBox_20)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.splitter_396 = QSplitter(self.groupBox_20)
        self.splitter_396.setObjectName(u"splitter_396")
        self.splitter_396.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_396.setHandleWidth(0)
        self.label_198 = QLabel(self.splitter_396)
        self.label_198.setObjectName(u"label_198")
        self.splitter_396.addWidget(self.label_198)
        self.comboBox_13 = QComboBox(self.splitter_396)
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.setObjectName(u"comboBox_13")
        self.splitter_396.addWidget(self.comboBox_13)

        self.gridLayout_3.addWidget(self.splitter_396, 0, 0, 1, 1)

        self.splitter_401 = QSplitter(self.groupBox_20)
        self.splitter_401.setObjectName(u"splitter_401")
        self.splitter_401.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_401.setHandleWidth(0)
        self.label_203 = QLabel(self.splitter_401)
        self.label_203.setObjectName(u"label_203")
        self.splitter_401.addWidget(self.label_203)
        self.comboBox_12 = QComboBox(self.splitter_401)
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.setObjectName(u"comboBox_12")
        self.splitter_401.addWidget(self.comboBox_12)

        self.gridLayout_3.addWidget(self.splitter_401, 1, 0, 1, 1)

        self.splitter_404 = QSplitter(self.groupBox_20)
        self.splitter_404.setObjectName(u"splitter_404")
        self.splitter_404.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_404.setHandleWidth(0)
        self.label_206 = QLabel(self.splitter_404)
        self.label_206.setObjectName(u"label_206")
        self.splitter_404.addWidget(self.label_206)
        self.comboBox_11 = QComboBox(self.splitter_404)
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.setObjectName(u"comboBox_11")
        self.splitter_404.addWidget(self.comboBox_11)

        self.gridLayout_3.addWidget(self.splitter_404, 2, 0, 1, 1)

        self.splitter_400 = QSplitter(self.groupBox_20)
        self.splitter_400.setObjectName(u"splitter_400")
        self.splitter_400.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_400.setHandleWidth(0)
        self.label_202 = QLabel(self.splitter_400)
        self.label_202.setObjectName(u"label_202")
        self.splitter_400.addWidget(self.label_202)
        self.comboBox_10 = QComboBox(self.splitter_400)
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.setObjectName(u"comboBox_10")
        self.splitter_400.addWidget(self.comboBox_10)

        self.gridLayout_3.addWidget(self.splitter_400, 3, 0, 1, 1)

        self.splitter_398 = QSplitter(self.groupBox_20)
        self.splitter_398.setObjectName(u"splitter_398")
        self.splitter_398.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_398.setHandleWidth(0)
        self.label_200 = QLabel(self.splitter_398)
        self.label_200.setObjectName(u"label_200")
        self.splitter_398.addWidget(self.label_200)
        self.comboBox_9 = QComboBox(self.splitter_398)
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.setObjectName(u"comboBox_9")
        self.splitter_398.addWidget(self.comboBox_9)

        self.gridLayout_3.addWidget(self.splitter_398, 4, 0, 1, 1)

        self.splitter_402 = QSplitter(self.groupBox_20)
        self.splitter_402.setObjectName(u"splitter_402")
        self.splitter_402.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_402.setHandleWidth(0)
        self.label_204 = QLabel(self.splitter_402)
        self.label_204.setObjectName(u"label_204")
        self.splitter_402.addWidget(self.label_204)
        self.comboBox_8 = QComboBox(self.splitter_402)
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.setObjectName(u"comboBox_8")
        self.splitter_402.addWidget(self.comboBox_8)

        self.gridLayout_3.addWidget(self.splitter_402, 5, 0, 1, 1)

        self.splitter_399 = QSplitter(self.groupBox_20)
        self.splitter_399.setObjectName(u"splitter_399")
        self.splitter_399.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_399.setHandleWidth(0)
        self.label_201 = QLabel(self.splitter_399)
        self.label_201.setObjectName(u"label_201")
        self.splitter_399.addWidget(self.label_201)
        self.comboBox_7 = QComboBox(self.splitter_399)
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.setObjectName(u"comboBox_7")
        self.splitter_399.addWidget(self.comboBox_7)

        self.gridLayout_3.addWidget(self.splitter_399, 6, 0, 1, 1)

        self.splitter_397 = QSplitter(self.groupBox_20)
        self.splitter_397.setObjectName(u"splitter_397")
        self.splitter_397.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_397.setHandleWidth(0)
        self.label_199 = QLabel(self.splitter_397)
        self.label_199.setObjectName(u"label_199")
        self.splitter_397.addWidget(self.label_199)
        self.comboBox_6 = QComboBox(self.splitter_397)
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.splitter_397.addWidget(self.comboBox_6)

        self.gridLayout_3.addWidget(self.splitter_397, 7, 0, 1, 1)

        self.splitter_403 = QSplitter(self.groupBox_20)
        self.splitter_403.setObjectName(u"splitter_403")
        self.splitter_403.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_403.setHandleWidth(0)
        self.label_205 = QLabel(self.splitter_403)
        self.label_205.setObjectName(u"label_205")
        self.splitter_403.addWidget(self.label_205)
        self.comboBox_5 = QComboBox(self.splitter_403)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.splitter_403.addWidget(self.comboBox_5)

        self.gridLayout_3.addWidget(self.splitter_403, 8, 0, 1, 1)

        self.splitter_407 = QSplitter(self.groupBox_20)
        self.splitter_407.setObjectName(u"splitter_407")
        self.splitter_407.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_407.setHandleWidth(0)
        self.label_209 = QLabel(self.splitter_407)
        self.label_209.setObjectName(u"label_209")
        self.splitter_407.addWidget(self.label_209)
        self.comboBox_14 = QComboBox(self.splitter_407)
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.setObjectName(u"comboBox_14")
        self.splitter_407.addWidget(self.comboBox_14)

        self.gridLayout_3.addWidget(self.splitter_407, 9, 0, 1, 1)

        self.splitter_406 = QSplitter(self.groupBox_20)
        self.splitter_406.setObjectName(u"splitter_406")
        self.splitter_406.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_406.setHandleWidth(0)
        self.label_208 = QLabel(self.splitter_406)
        self.label_208.setObjectName(u"label_208")
        self.splitter_406.addWidget(self.label_208)
        self.comboBox_15 = QComboBox(self.splitter_406)
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.setObjectName(u"comboBox_15")
        self.splitter_406.addWidget(self.comboBox_15)

        self.gridLayout_3.addWidget(self.splitter_406, 10, 0, 1, 1)

        self.splitter_405 = QSplitter(self.groupBox_20)
        self.splitter_405.setObjectName(u"splitter_405")
        self.splitter_405.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_405.setHandleWidth(0)
        self.label_207 = QLabel(self.splitter_405)
        self.label_207.setObjectName(u"label_207")
        self.splitter_405.addWidget(self.label_207)
        self.comboBox_16 = QComboBox(self.splitter_405)
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.setObjectName(u"comboBox_16")
        self.splitter_405.addWidget(self.comboBox_16)

        self.gridLayout_3.addWidget(self.splitter_405, 11, 0, 1, 1)

        self.radioButton = QRadioButton(self.groupBox_20)
        self.radioButton.setObjectName(u"radioButton")

        self.gridLayout_3.addWidget(self.radioButton, 12, 0, 1, 1)

        self.pushButton_304 = QPushButton(self.groupBox_20)
        self.pushButton_304.setObjectName(u"pushButton_304")

        self.gridLayout_3.addWidget(self.pushButton_304, 13, 0, 1, 1)

        self.splitter_395.addWidget(self.groupBox_20)
        self.splitter_3.addWidget(self.splitter_395)

        self.gridLayout.addWidget(self.splitter_3, 0, 0, 1, 1)


        self.horizontalLayout.addWidget(self.frame)


        self.retranslateUi(light_tool)

        QMetaObject.connectSlotsByName(light_tool)
    # setupUi

    def retranslateUi(self, light_tool):
        light_tool.setWindowTitle(QCoreApplication.translate("light_tool", u"Form", None))
        self.label_168.setText(QCoreApplication.translate("light_tool", u"light", None))
        self.pushButton_293.setText(QCoreApplication.translate("light_tool", u"X", None))
        self.main_Firefly.setText(QCoreApplication.translate("light_tool", u"Firefly", None))
        self.main_Object_Light.setText(QCoreApplication.translate("light_tool", u"Object Light", None))
        self.main_lightning.setText(QCoreApplication.translate("light_tool", u"lightning", None))
        self.label_172.setText(QCoreApplication.translate("light_tool", u"sub functions", None))
        self.sub_pulse.setText(QCoreApplication.translate("light_tool", u"pulse", None))
        self.sub_flicker.setText(QCoreApplication.translate("light_tool", u"flicker", None))
        self.sub_glow_spread.setText(QCoreApplication.translate("light_tool", u"glow spread", None))
        self.sub_trail.setText(QCoreApplication.translate("light_tool", u"trail", None))
        self.sub_spark.setText(QCoreApplication.translate("light_tool", u"spark", None))
        self.sub_flash.setText(QCoreApplication.translate("light_tool", u"flash", None))
        self.sub_radius_glow.setText(QCoreApplication.translate("light_tool", u"radius glow", None))
        self.sub_focus_pulse.setText(QCoreApplication.translate("light_tool", u"focus pulse", None))
        self.pushButton_3.setText(QCoreApplication.translate("light_tool", u"branches", None))
        self.label_197.setText(QCoreApplication.translate("light_tool", u"setings", None))
        self.groupBox_20.setTitle("")
        self.label_198.setText(QCoreApplication.translate("light_tool", u"intensity", None))
        self.comboBox_13.setItemText(0, QCoreApplication.translate("light_tool", u"weak", None))
        self.comboBox_13.setItemText(1, QCoreApplication.translate("light_tool", u"strong", None))
        self.comboBox_13.setItemText(2, QCoreApplication.translate("light_tool", u"normal", None))

        self.label_203.setText(QCoreApplication.translate("light_tool", u"radius", None))
        self.comboBox_12.setItemText(0, QCoreApplication.translate("light_tool", u"weak", None))
        self.comboBox_12.setItemText(1, QCoreApplication.translate("light_tool", u"strong", None))
        self.comboBox_12.setItemText(2, QCoreApplication.translate("light_tool", u"normal", None))

        self.label_206.setText(QCoreApplication.translate("light_tool", u"pulse speed", None))
        self.comboBox_11.setItemText(0, QCoreApplication.translate("light_tool", u"weak", None))
        self.comboBox_11.setItemText(1, QCoreApplication.translate("light_tool", u"strong", None))
        self.comboBox_11.setItemText(2, QCoreApplication.translate("light_tool", u"normal", None))

        self.label_202.setText(QCoreApplication.translate("light_tool", u"flicker frequency", None))
        self.comboBox_10.setItemText(0, QCoreApplication.translate("light_tool", u"weak", None))
        self.comboBox_10.setItemText(1, QCoreApplication.translate("light_tool", u"strong", None))
        self.comboBox_10.setItemText(2, QCoreApplication.translate("light_tool", u"normal", None))

        self.label_200.setText(QCoreApplication.translate("light_tool", u"glow depth", None))
        self.comboBox_9.setItemText(0, QCoreApplication.translate("light_tool", u"weak", None))
        self.comboBox_9.setItemText(1, QCoreApplication.translate("light_tool", u"strong", None))
        self.comboBox_9.setItemText(2, QCoreApplication.translate("light_tool", u"normal", None))

        self.label_204.setText(QCoreApplication.translate("light_tool", u"opacity", None))
        self.comboBox_8.setItemText(0, QCoreApplication.translate("light_tool", u"weak", None))
        self.comboBox_8.setItemText(1, QCoreApplication.translate("light_tool", u"strong", None))
        self.comboBox_8.setItemText(2, QCoreApplication.translate("light_tool", u"normal", None))

        self.label_201.setText(QCoreApplication.translate("light_tool", u"count", None))
        self.comboBox_7.setItemText(0, QCoreApplication.translate("light_tool", u"weak", None))
        self.comboBox_7.setItemText(1, QCoreApplication.translate("light_tool", u"strong", None))
        self.comboBox_7.setItemText(2, QCoreApplication.translate("light_tool", u"normal", None))

        self.label_199.setText(QCoreApplication.translate("light_tool", u"frequency", None))
        self.comboBox_6.setItemText(0, QCoreApplication.translate("light_tool", u"weak", None))
        self.comboBox_6.setItemText(1, QCoreApplication.translate("light_tool", u"strong", None))
        self.comboBox_6.setItemText(2, QCoreApplication.translate("light_tool", u"normal", None))

        self.label_205.setText(QCoreApplication.translate("light_tool", u"duration   ", None))
        self.comboBox_5.setItemText(0, QCoreApplication.translate("light_tool", u"weak", None))
        self.comboBox_5.setItemText(1, QCoreApplication.translate("light_tool", u"strong", None))
        self.comboBox_5.setItemText(2, QCoreApplication.translate("light_tool", u"normal", None))

        self.label_209.setText(QCoreApplication.translate("light_tool", u"branch count", None))
        self.comboBox_14.setItemText(0, QCoreApplication.translate("light_tool", u"weak", None))
        self.comboBox_14.setItemText(1, QCoreApplication.translate("light_tool", u"strong", None))
        self.comboBox_14.setItemText(2, QCoreApplication.translate("light_tool", u"normal", None))

        self.label_208.setText(QCoreApplication.translate("light_tool", u"bolt width", None))
        self.comboBox_15.setItemText(0, QCoreApplication.translate("light_tool", u"weak", None))
        self.comboBox_15.setItemText(1, QCoreApplication.translate("light_tool", u"strong", None))
        self.comboBox_15.setItemText(2, QCoreApplication.translate("light_tool", u"normal", None))

        self.label_207.setText(QCoreApplication.translate("light_tool", u"light radius ", None))
        self.comboBox_16.setItemText(0, QCoreApplication.translate("light_tool", u"weak", None))
        self.comboBox_16.setItemText(1, QCoreApplication.translate("light_tool", u"strong", None))
        self.comboBox_16.setItemText(2, QCoreApplication.translate("light_tool", u"normal", None))

        self.radioButton.setText(QCoreApplication.translate("light_tool", u"sync with rain", None))
        self.pushButton_304.setText(QCoreApplication.translate("light_tool", u"color", None))
    # retranslateUi

