# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'weather_tool.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QGroupBox,
    QLabel, QPushButton, QSizePolicy, QSpinBox,
    QSplitter, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(280, 534)
        Form.setMaximumSize(QSize(280, 16777215))
        self.gridLayout = QGridLayout(Form)
        self.gridLayout.setObjectName(u"gridLayout")
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setMaximumSize(QSize(280, 16777215))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_2 = QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.splitter_322 = QSplitter(self.frame)
        self.splitter_322.setObjectName(u"splitter_322")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_322.sizePolicy().hasHeightForWidth())
        self.splitter_322.setSizePolicy(sizePolicy)
        self.splitter_322.setOrientation(Qt.Orientation.Vertical)
        self.splitter_322.setHandleWidth(0)
        self.splitter_323 = QSplitter(self.splitter_322)
        self.splitter_323.setObjectName(u"splitter_323")
        self.splitter_323.setMaximumSize(QSize(16777215, 24))
        self.splitter_323.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_323.setHandleWidth(0)
        self.pushButton_253 = QPushButton(self.splitter_323)
        self.pushButton_253.setObjectName(u"pushButton_253")
        self.splitter_323.addWidget(self.pushButton_253)
        self.pushButton_254 = QPushButton(self.splitter_323)
        self.pushButton_254.setObjectName(u"pushButton_254")
        self.splitter_323.addWidget(self.pushButton_254)
        self.pushButton_255 = QPushButton(self.splitter_323)
        self.pushButton_255.setObjectName(u"pushButton_255")
        self.splitter_323.addWidget(self.pushButton_255)
        self.pushButton_256 = QPushButton(self.splitter_323)
        self.pushButton_256.setObjectName(u"pushButton_256")
        self.splitter_323.addWidget(self.pushButton_256)
        self.splitter_322.addWidget(self.splitter_323)

        self.gridLayout_2.addWidget(self.splitter_322, 2, 0, 1, 1)

        self.splitter_325 = QSplitter(self.frame)
        self.splitter_325.setObjectName(u"splitter_325")
        self.splitter_325.setOrientation(Qt.Orientation.Vertical)
        self.splitter_325.setHandleWidth(0)
        self.splitter_326 = QSplitter(self.splitter_325)
        self.splitter_326.setObjectName(u"splitter_326")
        self.splitter_326.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_326.setHandleWidth(0)
        self.pushButton_257 = QPushButton(self.splitter_326)
        self.pushButton_257.setObjectName(u"pushButton_257")
        self.splitter_326.addWidget(self.pushButton_257)
        self.pushButton_258 = QPushButton(self.splitter_326)
        self.pushButton_258.setObjectName(u"pushButton_258")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pushButton_258.sizePolicy().hasHeightForWidth())
        self.pushButton_258.setSizePolicy(sizePolicy1)
        self.splitter_326.addWidget(self.pushButton_258)
        self.splitter_325.addWidget(self.splitter_326)
        self.splitter_327 = QSplitter(self.splitter_325)
        self.splitter_327.setObjectName(u"splitter_327")
        self.splitter_327.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_327.setHandleWidth(0)
        self.pushButton_259 = QPushButton(self.splitter_327)
        self.pushButton_259.setObjectName(u"pushButton_259")
        self.splitter_327.addWidget(self.pushButton_259)
        self.pushButton_260 = QPushButton(self.splitter_327)
        self.pushButton_260.setObjectName(u"pushButton_260")
        self.splitter_327.addWidget(self.pushButton_260)
        self.splitter_325.addWidget(self.splitter_327)

        self.gridLayout_2.addWidget(self.splitter_325, 4, 0, 1, 1)

        self.splitter_328 = QSplitter(self.frame)
        self.splitter_328.setObjectName(u"splitter_328")
        self.splitter_328.setOrientation(Qt.Orientation.Vertical)
        self.splitter_328.setHandleWidth(0)
        self.splitter_329 = QSplitter(self.splitter_328)
        self.splitter_329.setObjectName(u"splitter_329")
        self.splitter_329.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_329.setHandleWidth(0)
        self.pushButton_261 = QPushButton(self.splitter_329)
        self.pushButton_261.setObjectName(u"pushButton_261")
        sizePolicy1.setHeightForWidth(self.pushButton_261.sizePolicy().hasHeightForWidth())
        self.pushButton_261.setSizePolicy(sizePolicy1)
        self.splitter_329.addWidget(self.pushButton_261)
        self.pushButton_262 = QPushButton(self.splitter_329)
        self.pushButton_262.setObjectName(u"pushButton_262")
        self.splitter_329.addWidget(self.pushButton_262)
        self.splitter_328.addWidget(self.splitter_329)
        self.splitter_330 = QSplitter(self.splitter_328)
        self.splitter_330.setObjectName(u"splitter_330")
        self.splitter_330.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_330.setHandleWidth(0)
        self.splitter_328.addWidget(self.splitter_330)

        self.gridLayout_2.addWidget(self.splitter_328, 5, 0, 1, 1)

        self.label_162 = QLabel(self.frame)
        self.label_162.setObjectName(u"label_162")
        self.label_162.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_162, 3, 0, 1, 1)

        self.splitter_331 = QSplitter(self.frame)
        self.splitter_331.setObjectName(u"splitter_331")
        self.splitter_331.setOrientation(Qt.Orientation.Vertical)
        self.splitter_331.setHandleWidth(0)
        self.label_163 = QLabel(self.splitter_331)
        self.label_163.setObjectName(u"label_163")
        self.label_163.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter_331.addWidget(self.label_163)
        self.groupBox_17 = QGroupBox(self.splitter_331)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setMaximumSize(QSize(280, 16777215))
        self.gridLayout_55 = QGridLayout(self.groupBox_17)
        self.gridLayout_55.setObjectName(u"gridLayout_55")
        self.splitter_332 = QSplitter(self.groupBox_17)
        self.splitter_332.setObjectName(u"splitter_332")
        self.splitter_332.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_332.setHandleWidth(0)
        self.label_164 = QLabel(self.splitter_332)
        self.label_164.setObjectName(u"label_164")
        self.splitter_332.addWidget(self.label_164)
        self.spinBox_111 = QSpinBox(self.splitter_332)
        self.spinBox_111.setObjectName(u"spinBox_111")
        sizePolicy.setHeightForWidth(self.spinBox_111.sizePolicy().hasHeightForWidth())
        self.spinBox_111.setSizePolicy(sizePolicy)
        self.spinBox_111.setMinimumSize(QSize(100, 0))
        self.spinBox_111.setMaximumSize(QSize(120, 16777215))
        self.splitter_332.addWidget(self.spinBox_111)

        self.gridLayout_55.addWidget(self.splitter_332, 9, 0, 1, 1)

        self.splitter_338 = QSplitter(self.groupBox_17)
        self.splitter_338.setObjectName(u"splitter_338")
        self.splitter_338.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_338.setHandleWidth(0)
        self.label_170 = QLabel(self.splitter_338)
        self.label_170.setObjectName(u"label_170")
        self.splitter_338.addWidget(self.label_170)
        self.spinBox_117 = QSpinBox(self.splitter_338)
        self.spinBox_117.setObjectName(u"spinBox_117")
        sizePolicy.setHeightForWidth(self.spinBox_117.sizePolicy().hasHeightForWidth())
        self.spinBox_117.setSizePolicy(sizePolicy)
        self.spinBox_117.setMinimumSize(QSize(100, 0))
        self.spinBox_117.setMaximumSize(QSize(120, 16777215))
        self.splitter_338.addWidget(self.spinBox_117)

        self.gridLayout_55.addWidget(self.splitter_338, 6, 0, 1, 1)

        self.splitter_337 = QSplitter(self.groupBox_17)
        self.splitter_337.setObjectName(u"splitter_337")
        self.splitter_337.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_337.setHandleWidth(0)
        self.label_169 = QLabel(self.splitter_337)
        self.label_169.setObjectName(u"label_169")
        self.splitter_337.addWidget(self.label_169)
        self.spinBox_116 = QSpinBox(self.splitter_337)
        self.spinBox_116.setObjectName(u"spinBox_116")
        self.spinBox_116.setMaximumSize(QSize(100, 16777215))
        self.splitter_337.addWidget(self.spinBox_116)

        self.gridLayout_55.addWidget(self.splitter_337, 3, 0, 1, 1)

        self.splitter_342 = QSplitter(self.groupBox_17)
        self.splitter_342.setObjectName(u"splitter_342")
        self.splitter_342.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_342.setHandleWidth(0)
        self.label_174 = QLabel(self.splitter_342)
        self.label_174.setObjectName(u"label_174")
        self.splitter_342.addWidget(self.label_174)
        self.spinBox_121 = QSpinBox(self.splitter_342)
        self.spinBox_121.setObjectName(u"spinBox_121")
        self.splitter_342.addWidget(self.spinBox_121)

        self.gridLayout_55.addWidget(self.splitter_342, 0, 0, 1, 1)

        self.splitter_341 = QSplitter(self.groupBox_17)
        self.splitter_341.setObjectName(u"splitter_341")
        self.splitter_341.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_341.setHandleWidth(0)
        self.label_173 = QLabel(self.splitter_341)
        self.label_173.setObjectName(u"label_173")
        self.splitter_341.addWidget(self.label_173)
        self.spinBox_120 = QSpinBox(self.splitter_341)
        self.spinBox_120.setObjectName(u"spinBox_120")
        self.splitter_341.addWidget(self.spinBox_120)

        self.gridLayout_55.addWidget(self.splitter_341, 2, 0, 1, 1)

        self.splitter_334 = QSplitter(self.groupBox_17)
        self.splitter_334.setObjectName(u"splitter_334")
        self.splitter_334.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_334.setHandleWidth(0)
        self.label_166 = QLabel(self.splitter_334)
        self.label_166.setObjectName(u"label_166")
        self.splitter_334.addWidget(self.label_166)
        self.spinBox_113 = QSpinBox(self.splitter_334)
        self.spinBox_113.setObjectName(u"spinBox_113")
        sizePolicy.setHeightForWidth(self.spinBox_113.sizePolicy().hasHeightForWidth())
        self.spinBox_113.setSizePolicy(sizePolicy)
        self.spinBox_113.setMinimumSize(QSize(100, 0))
        self.spinBox_113.setMaximumSize(QSize(120, 16777215))
        self.splitter_334.addWidget(self.spinBox_113)

        self.gridLayout_55.addWidget(self.splitter_334, 4, 0, 1, 1)

        self.splitter_335 = QSplitter(self.groupBox_17)
        self.splitter_335.setObjectName(u"splitter_335")
        self.splitter_335.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_335.setHandleWidth(0)
        self.label_167 = QLabel(self.splitter_335)
        self.label_167.setObjectName(u"label_167")
        self.splitter_335.addWidget(self.label_167)
        self.spinBox_114 = QSpinBox(self.splitter_335)
        self.spinBox_114.setObjectName(u"spinBox_114")
        sizePolicy.setHeightForWidth(self.spinBox_114.sizePolicy().hasHeightForWidth())
        self.spinBox_114.setSizePolicy(sizePolicy)
        self.spinBox_114.setMinimumSize(QSize(100, 0))
        self.spinBox_114.setMaximumSize(QSize(120, 16777215))
        self.splitter_335.addWidget(self.spinBox_114)

        self.gridLayout_55.addWidget(self.splitter_335, 5, 0, 1, 1)

        self.pushButton_263 = QPushButton(self.groupBox_17)
        self.pushButton_263.setObjectName(u"pushButton_263")

        self.gridLayout_55.addWidget(self.pushButton_263, 10, 0, 1, 1)

        self.splitter_333 = QSplitter(self.groupBox_17)
        self.splitter_333.setObjectName(u"splitter_333")
        self.splitter_333.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_333.setHandleWidth(0)
        self.label_165 = QLabel(self.splitter_333)
        self.label_165.setObjectName(u"label_165")
        self.splitter_333.addWidget(self.label_165)
        self.spinBox_112 = QSpinBox(self.splitter_333)
        self.spinBox_112.setObjectName(u"spinBox_112")
        sizePolicy.setHeightForWidth(self.spinBox_112.sizePolicy().hasHeightForWidth())
        self.spinBox_112.setSizePolicy(sizePolicy)
        self.spinBox_112.setMinimumSize(QSize(100, 0))
        self.spinBox_112.setMaximumSize(QSize(120, 16777215))
        self.splitter_333.addWidget(self.spinBox_112)

        self.gridLayout_55.addWidget(self.splitter_333, 8, 0, 1, 1)

        self.splitter_339 = QSplitter(self.groupBox_17)
        self.splitter_339.setObjectName(u"splitter_339")
        self.splitter_339.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_339.setHandleWidth(0)
        self.label_171 = QLabel(self.splitter_339)
        self.label_171.setObjectName(u"label_171")
        self.splitter_339.addWidget(self.label_171)
        self.spinBox_118 = QSpinBox(self.splitter_339)
        self.spinBox_118.setObjectName(u"spinBox_118")
        sizePolicy.setHeightForWidth(self.spinBox_118.sizePolicy().hasHeightForWidth())
        self.spinBox_118.setSizePolicy(sizePolicy)
        self.spinBox_118.setMinimumSize(QSize(100, 0))
        self.spinBox_118.setMaximumSize(QSize(120, 16777215))
        self.splitter_339.addWidget(self.spinBox_118)

        self.gridLayout_55.addWidget(self.splitter_339, 7, 0, 1, 1)

        self.splitter_331.addWidget(self.groupBox_17)

        self.gridLayout_2.addWidget(self.splitter_331, 6, 0, 1, 1)

        self.splitter_301 = QSplitter(self.frame)
        self.splitter_301.setObjectName(u"splitter_301")
        self.splitter_301.setMaximumSize(QSize(16777215, 24))
        self.splitter_301.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_301.setHandleWidth(0)
        self.label_161 = QLabel(self.splitter_301)
        self.label_161.setObjectName(u"label_161")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_161.sizePolicy().hasHeightForWidth())
        self.label_161.setSizePolicy(sizePolicy2)
        self.label_161.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter_301.addWidget(self.label_161)
        self.pushButton_252 = QPushButton(self.splitter_301)
        self.pushButton_252.setObjectName(u"pushButton_252")
        sizePolicy.setHeightForWidth(self.pushButton_252.sizePolicy().hasHeightForWidth())
        self.pushButton_252.setSizePolicy(sizePolicy)
        self.pushButton_252.setMaximumSize(QSize(30, 30))
        self.splitter_301.addWidget(self.pushButton_252)

        self.gridLayout_2.addWidget(self.splitter_301, 1, 0, 1, 1)


        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)


        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.pushButton_253.setText(QCoreApplication.translate("Form", u"Fog", None))
        self.pushButton_254.setText(QCoreApplication.translate("Form", u"Wind ", None))
        self.pushButton_255.setText(QCoreApplication.translate("Form", u"Smoke ", None))
        self.pushButton_256.setText(QCoreApplication.translate("Form", u"Vapour ", None))
        self.pushButton_257.setText(QCoreApplication.translate("Form", u"swirls", None))
        self.pushButton_258.setText(QCoreApplication.translate("Form", u"drift", None))
        self.pushButton_259.setText(QCoreApplication.translate("Form", u"gusts", None))
        self.pushButton_260.setText(QCoreApplication.translate("Form", u"density pulse", None))
        self.pushButton_261.setText(QCoreApplication.translate("Form", u"fade fluctuations", None))
        self.pushButton_262.setText(QCoreApplication.translate("Form", u"heat lift", None))
        self.label_162.setText(QCoreApplication.translate("Form", u"sub functions", None))
        self.label_163.setText(QCoreApplication.translate("Form", u"setings", None))
        self.groupBox_17.setTitle("")
        self.label_164.setText(QCoreApplication.translate("Form", u"particle size", None))
        self.label_170.setText(QCoreApplication.translate("Form", u"pulse rate", None))
        self.label_169.setText(QCoreApplication.translate("Form", u"lift", None))
        self.label_174.setText(QCoreApplication.translate("Form", u"drift speed", None))
        self.label_173.setText(QCoreApplication.translate("Form", u"intensity ", None))
        self.label_166.setText(QCoreApplication.translate("Form", u"density", None))
        self.label_167.setText(QCoreApplication.translate("Form", u"randomness", None))
        self.pushButton_263.setText(QCoreApplication.translate("Form", u"color", None))
        self.label_165.setText(QCoreApplication.translate("Form", u"glow pulse", None))
        self.label_171.setText(QCoreApplication.translate("Form", u"blur", None))
        self.label_161.setText(QCoreApplication.translate("Form", u"weather", None))
        self.pushButton_252.setText(QCoreApplication.translate("Form", u"X", None))
    # retranslateUi

