# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'weather_tool.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGridLayout,
    QGroupBox, QLabel, QPushButton, QSizePolicy,
    QSplitter, QWidget)

class Ui_weather_tool(object):
    def setupUi(self, weather_tool):
        if not weather_tool.objectName():
            weather_tool.setObjectName(u"weather_tool")
        weather_tool.resize(280, 534)
        weather_tool.setMaximumSize(QSize(280, 16777215))
        self.gridLayout = QGridLayout(weather_tool)
        self.gridLayout.setObjectName(u"gridLayout")
        self.frame = QFrame(weather_tool)
        self.frame.setObjectName(u"frame")
        self.frame.setMaximumSize(QSize(280, 16777215))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_2 = QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.splitter_322 = QSplitter(self.frame)
        self.splitter_322.setObjectName(u"splitter_322")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_322.sizePolicy().hasHeightForWidth())
        self.splitter_322.setSizePolicy(sizePolicy)
        self.splitter_322.setOrientation(Qt.Orientation.Vertical)
        self.splitter_322.setHandleWidth(0)
        self.splitter_323 = QSplitter(self.splitter_322)
        self.splitter_323.setObjectName(u"splitter_323")
        self.splitter_323.setMaximumSize(QSize(16777215, 24))
        self.splitter_323.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_323.setHandleWidth(0)
        self.main_Fog = QPushButton(self.splitter_323)
        self.main_Fog.setObjectName(u"main_Fog")
        self.splitter_323.addWidget(self.main_Fog)
        self.main_Wind = QPushButton(self.splitter_323)
        self.main_Wind.setObjectName(u"main_Wind")
        self.splitter_323.addWidget(self.main_Wind)
        self.main_Smoke = QPushButton(self.splitter_323)
        self.main_Smoke.setObjectName(u"main_Smoke")
        self.splitter_323.addWidget(self.main_Smoke)
        self.main_Vapour = QPushButton(self.splitter_323)
        self.main_Vapour.setObjectName(u"main_Vapour")
        self.splitter_323.addWidget(self.main_Vapour)
        self.splitter_322.addWidget(self.splitter_323)

        self.gridLayout_2.addWidget(self.splitter_322, 2, 0, 1, 1)

        self.splitter_325 = QSplitter(self.frame)
        self.splitter_325.setObjectName(u"splitter_325")
        self.splitter_325.setOrientation(Qt.Orientation.Vertical)
        self.splitter_325.setHandleWidth(0)
        self.splitter_326 = QSplitter(self.splitter_325)
        self.splitter_326.setObjectName(u"splitter_326")
        self.splitter_326.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_326.setHandleWidth(0)
        self.sub_swirls = QPushButton(self.splitter_326)
        self.sub_swirls.setObjectName(u"sub_swirls")
        self.splitter_326.addWidget(self.sub_swirls)
        self.sub_drift = QPushButton(self.splitter_326)
        self.sub_drift.setObjectName(u"sub_drift")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.sub_drift.sizePolicy().hasHeightForWidth())
        self.sub_drift.setSizePolicy(sizePolicy1)
        self.splitter_326.addWidget(self.sub_drift)
        self.splitter_325.addWidget(self.splitter_326)
        self.splitter_327 = QSplitter(self.splitter_325)
        self.splitter_327.setObjectName(u"splitter_327")
        self.splitter_327.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_327.setHandleWidth(0)
        self.sub_gusts = QPushButton(self.splitter_327)
        self.sub_gusts.setObjectName(u"sub_gusts")
        self.splitter_327.addWidget(self.sub_gusts)
        self.sub_density_pulse = QPushButton(self.splitter_327)
        self.sub_density_pulse.setObjectName(u"sub_density_pulse")
        self.splitter_327.addWidget(self.sub_density_pulse)
        self.splitter_325.addWidget(self.splitter_327)

        self.gridLayout_2.addWidget(self.splitter_325, 4, 0, 1, 1)

        self.splitter_328 = QSplitter(self.frame)
        self.splitter_328.setObjectName(u"splitter_328")
        self.splitter_328.setOrientation(Qt.Orientation.Vertical)
        self.splitter_328.setHandleWidth(0)
        self.splitter_329 = QSplitter(self.splitter_328)
        self.splitter_329.setObjectName(u"splitter_329")
        self.splitter_329.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_329.setHandleWidth(0)
        self.sub_fade_fluctuations = QPushButton(self.splitter_329)
        self.sub_fade_fluctuations.setObjectName(u"sub_fade_fluctuations")
        sizePolicy1.setHeightForWidth(self.sub_fade_fluctuations.sizePolicy().hasHeightForWidth())
        self.sub_fade_fluctuations.setSizePolicy(sizePolicy1)
        self.splitter_329.addWidget(self.sub_fade_fluctuations)
        self.sub_heat_lift = QPushButton(self.splitter_329)
        self.sub_heat_lift.setObjectName(u"sub_heat_lift")
        self.splitter_329.addWidget(self.sub_heat_lift)
        self.splitter_328.addWidget(self.splitter_329)
        self.splitter_330 = QSplitter(self.splitter_328)
        self.splitter_330.setObjectName(u"splitter_330")
        self.splitter_330.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_330.setHandleWidth(0)
        self.splitter_328.addWidget(self.splitter_330)

        self.gridLayout_2.addWidget(self.splitter_328, 5, 0, 1, 1)

        self.label_162 = QLabel(self.frame)
        self.label_162.setObjectName(u"label_162")
        self.label_162.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_162, 3, 0, 1, 1)

        self.splitter_331 = QSplitter(self.frame)
        self.splitter_331.setObjectName(u"splitter_331")
        self.splitter_331.setOrientation(Qt.Orientation.Vertical)
        self.splitter_331.setHandleWidth(0)
        self.label_163 = QLabel(self.splitter_331)
        self.label_163.setObjectName(u"label_163")
        self.label_163.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter_331.addWidget(self.label_163)
        self.groupBox_17 = QGroupBox(self.splitter_331)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setMaximumSize(QSize(280, 16777215))
        self.gridLayout_55 = QGridLayout(self.groupBox_17)
        self.gridLayout_55.setObjectName(u"gridLayout_55")
        self.splitter_332 = QSplitter(self.groupBox_17)
        self.splitter_332.setObjectName(u"splitter_332")
        self.splitter_332.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_332.setHandleWidth(0)
        self.label_164 = QLabel(self.splitter_332)
        self.label_164.setObjectName(u"label_164")
        self.splitter_332.addWidget(self.label_164)
        self.comboBox_13 = QComboBox(self.splitter_332)
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.setObjectName(u"comboBox_13")
        self.splitter_332.addWidget(self.comboBox_13)

        self.gridLayout_55.addWidget(self.splitter_332, 9, 0, 1, 1)

        self.splitter_338 = QSplitter(self.groupBox_17)
        self.splitter_338.setObjectName(u"splitter_338")
        self.splitter_338.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_338.setHandleWidth(0)
        self.label_170 = QLabel(self.splitter_338)
        self.label_170.setObjectName(u"label_170")
        self.splitter_338.addWidget(self.label_170)
        self.comboBox_11 = QComboBox(self.splitter_338)
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.setObjectName(u"comboBox_11")
        self.splitter_338.addWidget(self.comboBox_11)

        self.gridLayout_55.addWidget(self.splitter_338, 6, 0, 1, 1)

        self.splitter_337 = QSplitter(self.groupBox_17)
        self.splitter_337.setObjectName(u"splitter_337")
        self.splitter_337.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_337.setHandleWidth(0)
        self.label_169 = QLabel(self.splitter_337)
        self.label_169.setObjectName(u"label_169")
        self.splitter_337.addWidget(self.label_169)
        self.comboBox_9 = QComboBox(self.splitter_337)
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.setObjectName(u"comboBox_9")
        self.splitter_337.addWidget(self.comboBox_9)

        self.gridLayout_55.addWidget(self.splitter_337, 3, 0, 1, 1)

        self.splitter_342 = QSplitter(self.groupBox_17)
        self.splitter_342.setObjectName(u"splitter_342")
        self.splitter_342.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_342.setHandleWidth(0)
        self.label_174 = QLabel(self.splitter_342)
        self.label_174.setObjectName(u"label_174")
        self.splitter_342.addWidget(self.label_174)
        self.comboBox_6 = QComboBox(self.splitter_342)
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.splitter_342.addWidget(self.comboBox_6)

        self.gridLayout_55.addWidget(self.splitter_342, 0, 0, 1, 1)

        self.splitter_341 = QSplitter(self.groupBox_17)
        self.splitter_341.setObjectName(u"splitter_341")
        self.splitter_341.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_341.setHandleWidth(0)
        self.label_173 = QLabel(self.splitter_341)
        self.label_173.setObjectName(u"label_173")
        self.splitter_341.addWidget(self.label_173)
        self.comboBox_10 = QComboBox(self.splitter_341)
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.setObjectName(u"comboBox_10")
        self.splitter_341.addWidget(self.comboBox_10)

        self.gridLayout_55.addWidget(self.splitter_341, 2, 0, 1, 1)

        self.splitter_334 = QSplitter(self.groupBox_17)
        self.splitter_334.setObjectName(u"splitter_334")
        self.splitter_334.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_334.setHandleWidth(0)
        self.label_166 = QLabel(self.splitter_334)
        self.label_166.setObjectName(u"label_166")
        self.splitter_334.addWidget(self.label_166)
        self.comboBox_8 = QComboBox(self.splitter_334)
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.setObjectName(u"comboBox_8")
        self.splitter_334.addWidget(self.comboBox_8)

        self.gridLayout_55.addWidget(self.splitter_334, 4, 0, 1, 1)

        self.splitter_335 = QSplitter(self.groupBox_17)
        self.splitter_335.setObjectName(u"splitter_335")
        self.splitter_335.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_335.setHandleWidth(0)
        self.label_167 = QLabel(self.splitter_335)
        self.label_167.setObjectName(u"label_167")
        self.splitter_335.addWidget(self.label_167)
        self.comboBox_7 = QComboBox(self.splitter_335)
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.setObjectName(u"comboBox_7")
        self.splitter_335.addWidget(self.comboBox_7)

        self.gridLayout_55.addWidget(self.splitter_335, 5, 0, 1, 1)

        self.pushButton_263 = QPushButton(self.groupBox_17)
        self.pushButton_263.setObjectName(u"pushButton_263")

        self.gridLayout_55.addWidget(self.pushButton_263, 10, 0, 1, 1)

        self.splitter_333 = QSplitter(self.groupBox_17)
        self.splitter_333.setObjectName(u"splitter_333")
        self.splitter_333.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_333.setHandleWidth(0)
        self.label_165 = QLabel(self.splitter_333)
        self.label_165.setObjectName(u"label_165")
        self.splitter_333.addWidget(self.label_165)
        self.comboBox_12 = QComboBox(self.splitter_333)
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.setObjectName(u"comboBox_12")
        self.splitter_333.addWidget(self.comboBox_12)

        self.gridLayout_55.addWidget(self.splitter_333, 8, 0, 1, 1)

        self.splitter_339 = QSplitter(self.groupBox_17)
        self.splitter_339.setObjectName(u"splitter_339")
        self.splitter_339.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_339.setHandleWidth(0)
        self.label_171 = QLabel(self.splitter_339)
        self.label_171.setObjectName(u"label_171")
        self.splitter_339.addWidget(self.label_171)
        self.comboBox_5 = QComboBox(self.splitter_339)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.splitter_339.addWidget(self.comboBox_5)

        self.gridLayout_55.addWidget(self.splitter_339, 7, 0, 1, 1)

        self.splitter_331.addWidget(self.groupBox_17)

        self.gridLayout_2.addWidget(self.splitter_331, 6, 0, 1, 1)

        self.splitter_301 = QSplitter(self.frame)
        self.splitter_301.setObjectName(u"splitter_301")
        self.splitter_301.setMaximumSize(QSize(16777215, 24))
        self.splitter_301.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_301.setHandleWidth(0)
        self.label_161 = QLabel(self.splitter_301)
        self.label_161.setObjectName(u"label_161")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_161.sizePolicy().hasHeightForWidth())
        self.label_161.setSizePolicy(sizePolicy2)
        self.label_161.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.splitter_301.addWidget(self.label_161)
        self.pushButton_252 = QPushButton(self.splitter_301)
        self.pushButton_252.setObjectName(u"pushButton_252")
        sizePolicy.setHeightForWidth(self.pushButton_252.sizePolicy().hasHeightForWidth())
        self.pushButton_252.setSizePolicy(sizePolicy)
        self.pushButton_252.setMaximumSize(QSize(30, 30))
        self.splitter_301.addWidget(self.pushButton_252)

        self.gridLayout_2.addWidget(self.splitter_301, 1, 0, 1, 1)


        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)


        self.retranslateUi(weather_tool)

        QMetaObject.connectSlotsByName(weather_tool)
    # setupUi

    def retranslateUi(self, weather_tool):
        weather_tool.setWindowTitle(QCoreApplication.translate("weather_tool", u"Form", None))
        self.main_Fog.setText(QCoreApplication.translate("weather_tool", u"Fog", None))
        self.main_Wind.setText(QCoreApplication.translate("weather_tool", u"Wind ", None))
        self.main_Smoke.setText(QCoreApplication.translate("weather_tool", u"Smoke ", None))
        self.main_Vapour.setText(QCoreApplication.translate("weather_tool", u"Vapour ", None))
        self.sub_swirls.setText(QCoreApplication.translate("weather_tool", u"swirls", None))
        self.sub_drift.setText(QCoreApplication.translate("weather_tool", u"drift", None))
        self.sub_gusts.setText(QCoreApplication.translate("weather_tool", u"gusts", None))
        self.sub_density_pulse.setText(QCoreApplication.translate("weather_tool", u"density pulse", None))
        self.sub_fade_fluctuations.setText(QCoreApplication.translate("weather_tool", u"fade fluctuations", None))
        self.sub_heat_lift.setText(QCoreApplication.translate("weather_tool", u"heat lift", None))
        self.label_162.setText(QCoreApplication.translate("weather_tool", u"sub functions", None))
        self.label_163.setText(QCoreApplication.translate("weather_tool", u"setings", None))
        self.groupBox_17.setTitle("")
        self.label_164.setText(QCoreApplication.translate("weather_tool", u"particle size", None))
        self.comboBox_13.setItemText(0, QCoreApplication.translate("weather_tool", u"weak", None))
        self.comboBox_13.setItemText(1, QCoreApplication.translate("weather_tool", u"strong", None))
        self.comboBox_13.setItemText(2, QCoreApplication.translate("weather_tool", u"normal", None))

        self.label_170.setText(QCoreApplication.translate("weather_tool", u"pulse rate", None))
        self.comboBox_11.setItemText(0, QCoreApplication.translate("weather_tool", u"weak", None))
        self.comboBox_11.setItemText(1, QCoreApplication.translate("weather_tool", u"strong", None))
        self.comboBox_11.setItemText(2, QCoreApplication.translate("weather_tool", u"normal", None))

        self.label_169.setText(QCoreApplication.translate("weather_tool", u"lift", None))
        self.comboBox_9.setItemText(0, QCoreApplication.translate("weather_tool", u"weak", None))
        self.comboBox_9.setItemText(1, QCoreApplication.translate("weather_tool", u"strong", None))
        self.comboBox_9.setItemText(2, QCoreApplication.translate("weather_tool", u"normal", None))

        self.label_174.setText(QCoreApplication.translate("weather_tool", u"drift speed", None))
        self.comboBox_6.setItemText(0, QCoreApplication.translate("weather_tool", u"weak", None))
        self.comboBox_6.setItemText(1, QCoreApplication.translate("weather_tool", u"strong", None))
        self.comboBox_6.setItemText(2, QCoreApplication.translate("weather_tool", u"normal", None))

        self.label_173.setText(QCoreApplication.translate("weather_tool", u"intensity ", None))
        self.comboBox_10.setItemText(0, QCoreApplication.translate("weather_tool", u"weak", None))
        self.comboBox_10.setItemText(1, QCoreApplication.translate("weather_tool", u"strong", None))
        self.comboBox_10.setItemText(2, QCoreApplication.translate("weather_tool", u"normal", None))

        self.label_166.setText(QCoreApplication.translate("weather_tool", u"density", None))
        self.comboBox_8.setItemText(0, QCoreApplication.translate("weather_tool", u"weak", None))
        self.comboBox_8.setItemText(1, QCoreApplication.translate("weather_tool", u"strong", None))
        self.comboBox_8.setItemText(2, QCoreApplication.translate("weather_tool", u"normal", None))

        self.label_167.setText(QCoreApplication.translate("weather_tool", u"randomness", None))
        self.comboBox_7.setItemText(0, QCoreApplication.translate("weather_tool", u"weak", None))
        self.comboBox_7.setItemText(1, QCoreApplication.translate("weather_tool", u"strong", None))
        self.comboBox_7.setItemText(2, QCoreApplication.translate("weather_tool", u"normal", None))

        self.pushButton_263.setText(QCoreApplication.translate("weather_tool", u"color", None))
        self.label_165.setText(QCoreApplication.translate("weather_tool", u"glow pulse", None))
        self.comboBox_12.setItemText(0, QCoreApplication.translate("weather_tool", u"weak", None))
        self.comboBox_12.setItemText(1, QCoreApplication.translate("weather_tool", u"strong", None))
        self.comboBox_12.setItemText(2, QCoreApplication.translate("weather_tool", u"normal", None))

        self.label_171.setText(QCoreApplication.translate("weather_tool", u"blur", None))
        self.comboBox_5.setItemText(0, QCoreApplication.translate("weather_tool", u"weak", None))
        self.comboBox_5.setItemText(1, QCoreApplication.translate("weather_tool", u"strong", None))
        self.comboBox_5.setItemText(2, QCoreApplication.translate("weather_tool", u"normal", None))

        self.label_161.setText(QCoreApplication.translate("weather_tool", u"weather", None))
        self.pushButton_252.setText(QCoreApplication.translate("weather_tool", u"X", None))
    # retranslateUi

